/**
 * Emerging Asia-Pacific case studies researched through 9 August 2026.
 *
 * Contested legal, political, economic, and environmental claims remain
 * attributed to their sources. Review dates are editorial checkpoints rather
 * than predictions about when the underlying situation will change.
 */
export const ASIA_PACIFIC_CASE_STUDIES_2026 = [
    {
        id: 'indus-water-regime-under-strain',
        title: 'Indus Waters Treaty: Security, Law, and Basin Livelihoods',
        subtitle: 'When a river-sharing framework becomes part of a wider security confrontation',
        regionTags: ['Asia-Pacific', 'South Asia', 'Indus Basin'],
        coverageRegion: 'South Asia',
        issueDimensions: ['Transboundary water', 'International law', 'Interstate security', 'Food and livelihoods'],
        actors: ['India', 'Pakistan', 'Indus basin communities', 'Permanent Court of Arbitration registry'],
        nexusNodeIds: ['AsiaPacific', 'UN_OPEC'],
        statusSummary: 'India says it has placed the Indus Waters Treaty in abeyance as part of its security response, while Pakistan rejects unilateral abeyance and says the treaty remains binding. The Permanent Court of Arbitration reported continuing proceedings under the treaty in February 2026. These are distinct attributed legal and policy positions, not a settled account of the treaty\'s present legal operation.',
        whyItMatters: 'The case links deterrence and treaty compliance to irrigation, hydropower, food security, and the daily needs of communities that cannot be separated from a shared river system.',
        updatedAt: '2026-02-09',
        confidence: 'medium',
        uncertainty: 'The parties dispute both the legal effect of India\'s action and the authority of ongoing proceedings. Project operations and basin conditions also change independently of the diplomatic dispute.',
        coordinates: { latitude: 32.5, longitude: 73.5 },
        broadCategory: 'Climate, Resources & Security',
        featured: true,
        sensitivity: 'high',
        reviewCadenceDays: 14,
        reviewBy: '2026-08-23',
        map: {
            mode: 'route',
            locations: [
                { label: 'New Delhi', latitude: 28.6139, longitude: 77.209 },
                { label: 'Srinagar', latitude: 34.0837, longitude: 74.7973 },
                { label: 'Tarbela', latitude: 34.0894, longitude: 72.6987 },
                { label: 'Islamabad', latitude: 33.6844, longitude: 73.0479 },
            ],
        },
        sources: [
            {
                title: 'Statement by the Spokesperson Regarding Indian Home Minister\'s Assertion that the Indus Waters Treaty Will Never be Restored',
                publisher: 'Ministry of Foreign Affairs, Government of Pakistan',
                publishedAt: '2025-06-21',
                url: 'https://mofa.gov.pk/press-releases/statement-by-the-spokesperson-regarding-indian-home-ministers-assertion-that-the-indus-waters-treaty-will-never-be-restored',
                perspectiveType: 'local',
                perspective: 'Official Pakistani treaty-law and water-security position',
                supports: 'Pakistan\'s attributed rejection of unilateral abeyance and its stated commitment to the treaty',
            },
            {
                title: 'PCA Case No. 2023-01: The Indus Waters Western Rivers Arbitration',
                publisher: 'Permanent Court of Arbitration',
                publishedAt: '2026-02-09',
                url: 'https://pca-cpa.org/en/news/pca-press-release-pca-case-no-2023-01-the-indus-waters-western-rivers-arbitration-islamic-republic-of-pakistan-v-republic-of-india-3/',
                perspectiveType: 'institutional',
                perspective: 'Arbitral registry account of proceedings conducted under the treaty framework',
                supports: 'The continuation of institutional adjudication despite disagreement between the parties',
            },
            {
                title: 'India–Pakistan ceasefire remains shaky, with relations unlikely to return to status quo',
                publisher: 'Chatham House',
                publishedAt: '2025-06-05',
                url: 'https://www.chathamhouse.org/2025/05/india-pakistan-ceasefire-remains-shaky-relations-unlikely-return-status-quo',
                perspectiveType: 'independent',
                perspective: 'Independent regional-security analysis of Indian and Pakistani positions',
                supports: 'How the water dispute became embedded in a wider breakdown of bilateral relations',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'India\'s Security Rationale',
                perspectiveLabel: 'Indian policy position',
                perspectiveType: 'local',
                narration: 'India\'s government has described treaty abeyance as part of its response to security threats. The case record treats that as an attributed policy position rather than a neutral legal conclusion.',
                focusQuestion: 'When, if ever, should a security crisis change how a state performs a long-running resource treaty?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'Pakistan\'s Treaty Claim',
                perspectiveLabel: 'Pakistani policy position',
                perspectiveType: 'local',
                narration: 'Pakistan\'s Foreign Ministry argues that the treaty contains no route for unilateral abeyance and frames reliable river flows as a legal and livelihood concern.',
                focusQuestion: 'How can a downstream state protect essential water interests when the parties disagree over the rules themselves?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Adjudication Without Consensus',
                perspectiveLabel: 'Treaty institution',
                perspectiveType: 'institutional',
                narration: 'Proceedings registered through the Permanent Court of Arbitration continued in 2026 even as India and Pakistan disputed their legal significance.',
                focusQuestion: 'What practical influence can an arbitral process retain when one party rejects its authority?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'The Basin Beyond the Capitals',
                perspectiveLabel: 'Basin livelihoods',
                perspectiveType: 'independent',
                narration: 'Farmers, electricity users, and river ecosystems experience the consequences of uncertainty even though national-security arguments dominate the public debate.',
                focusQuestion: 'Which indicators would show whether diplomatic pressure is becoming material harm for basin communities?',
            },
        ],
    },
    {
        id: 'bangladesh-ldc-graduation-decision',
        title: 'Bangladesh at the Graduation Gate',
        subtitle: 'Trade preferences, domestic reform, and the contested timing of LDC graduation',
        regionTags: ['Asia-Pacific', 'South Asia', 'Bangladesh'],
        coverageRegion: 'South Asia',
        issueDimensions: ['Development finance', 'Trade preferences', 'Industrial policy', 'Labor and public health'],
        actors: ['Government of Bangladesh', 'Bangladeshi exporters and workers', 'UN Committee for Development Policy', 'Trading partners'],
        nexusNodeIds: ['AsiaPacific', 'UN_OPEC', 'Europe', 'BiotechHub'],
        statusSummary: 'Bangladesh remains scheduled to graduate from least-developed-country status on 24 November 2026, while its government has requested an extension of the preparatory period to 2029. The UN Committee for Development Policy recommended favorable consideration subject to continued reform progress; a final General Assembly decision remained unresolved in the cited record.',
        whyItMatters: 'Graduation can signal development progress while also changing trade preferences, financing terms, pharmaceutical flexibilities, and the adjustment pressures borne by workers and export industries.',
        updatedAt: '2026-06-02',
        confidence: 'high',
        uncertainty: 'The General Assembly decision, partner-country transition arrangements, and domestic reform timetable may change quickly before the scheduled graduation date.',
        coordinates: { latitude: 23.8103, longitude: 90.4125 },
        broadCategory: 'Global Governance & Economics',
        featured: true,
        sensitivity: 'standard',
        reviewCadenceDays: 14,
        reviewBy: '2026-08-23',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Dhaka', latitude: 23.8103, longitude: 90.4125 },
                { label: 'Chattogram', latitude: 22.3569, longitude: 91.7832 },
                { label: 'Geneva', latitude: 46.2044, longitude: 6.1432 },
                { label: 'Brussels', latitude: 50.8503, longitude: 4.3517 },
            ],
        },
        sources: [
            {
                title: 'CDP recommends favorable consideration of Bangladesh\'s request for extension of LDC graduation preparatory period',
                publisher: 'Government of Bangladesh, Support to Sustainable Graduation Project',
                publishedAt: '2026-06-02',
                url: 'https://ssgp.erd.gov.bd/news-posts/cdp-recommends-favorable-consideration-of-bangladeshs-request-for-extension-of-ldc-graduation-preparatory-period/',
                perspectiveType: 'local',
                perspective: 'Bangladesh government account of its extension request and transition preparations',
                supports: 'The requested 2029 extension and the government\'s account of the CDP response',
            },
            {
                title: 'Bangladesh graduation status and preparatory-period extension request',
                publisher: 'United Nations LDC Portal',
                publishedAt: '2026-02-18',
                url: 'https://www.un.org/ldcportal/node/858',
                perspectiveType: 'institutional',
                perspective: 'United Nations status record for the graduation and decision process',
                supports: 'The scheduled graduation date, formal extension request, and multilateral decision path',
            },
            {
                title: 'Deferring Bangladesh\'s LDC graduation and the road ahead',
                publisher: 'Centre for Policy Dialogue',
                publishedAt: '2026-02-23',
                url: 'https://cpd.org.bd/deferring-bangladeshs-ldc-graduation-and-the-road-ahead/',
                perspectiveType: 'independent',
                perspective: 'Independent Bangladeshi policy analysis of readiness and post-graduation reform',
                supports: 'Why competitiveness, governance, and transition measures matter with or without a deferral',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'Readiness at Home',
                perspectiveLabel: 'Bangladesh government',
                perspectiveType: 'local',
                narration: 'The government requested more preparation time while presenting the extension as a way to secure a smoother and more durable transition.',
                focusQuestion: 'Which reforms would justify additional preparation time, and how should progress be measured?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'The Multilateral Decision Gate',
                perspectiveLabel: 'United Nations process',
                perspectiveType: 'institutional',
                narration: 'Graduation follows UN criteria and a General Assembly process, but exceptional shocks and transition capacity can shape the timetable.',
                focusQuestion: 'How should a rules-based graduation system respond when eligibility and readiness point in different directions?',
            },
            {
                nodeId: 'Europe',
                title: 'Preferences and Market Access',
                perspectiveLabel: 'Trading partners and exporters',
                perspectiveType: 'independent',
                narration: 'Export sectors must prepare for changing preference regimes and tougher compliance expectations in major markets, including Europe.',
                focusQuestion: 'Who should carry the cost of meeting new standards: firms, workers, the state, or trading partners?',
            },
            {
                nodeId: 'BiotechHub',
                title: 'Medicines and Social Adjustment',
                perspectiveLabel: 'Public-interest transition',
                perspectiveType: 'independent',
                narration: 'Changes to LDC-specific flexibilities can affect pharmaceutical policy, while industrial adjustment can affect employment and household resilience.',
                focusQuestion: 'How can graduation preserve development gains for workers and patients as formal preferences change?',
            },
        ],
    },
    {
        id: 'kyrgyzstan-tajikistan-border-peace',
        title: 'Kyrgyzstan–Tajikistan: From Border Treaty to Everyday Peace',
        subtitle: 'Turning a state-level settlement into security and trust in the Ferghana Valley',
        regionTags: ['Asia-Pacific', 'Central Asia', 'Ferghana Valley'],
        coverageRegion: 'Central Asia',
        issueDimensions: ['Border settlement', 'Peacebuilding', 'Water and land access', 'Regional diplomacy'],
        actors: ['Kyrgyz Republic', 'Tajikistan', 'Border communities', 'Women peacebuilders', 'United Nations country team'],
        nexusNodeIds: ['AsiaPacific', 'UN_OPEC', 'Russia'],
        statusSummary: 'Kyrgyzstan and Tajikistan signed a border treaty and reopened crossings in March 2025, moving the dispute into an implementation phase. Independent and UN reporting indicates that durable peace still depends on local trust, access to land and water, inclusive institutions, and the ability to manage future disputes without renewed violence.',
        whyItMatters: 'The settlement is a rare opportunity to study whether elite diplomacy can resolve territorial disagreement while also repairing the community relationships and resource arrangements damaged by earlier clashes.',
        updatedAt: '2026-01-19',
        confidence: 'high',
        uncertainty: 'The treaty reduces formal territorial uncertainty, but local implementation, property access, infrastructure, and public acceptance remain uneven and less visible than national ceremonies.',
        coordinates: { latitude: 40.0626, longitude: 70.8194 },
        broadCategory: 'Geopolitics & Conflict',
        featured: true,
        sensitivity: 'high',
        reviewCadenceDays: 60,
        reviewBy: '2026-10-08',
        map: {
            mode: 'route',
            locations: [
                { label: 'Bishkek', latitude: 42.8746, longitude: 74.5698 },
                { label: 'Batken', latitude: 40.0626, longitude: 70.8194 },
                { label: 'Khujand', latitude: 40.2833, longitude: 69.6222 },
                { label: 'Dushanbe', latitude: 38.5598, longitude: 68.787 },
            ],
        },
        sources: [
            {
                title: 'Kairagach and Kyzyl-Bel checkpoints resume operations on the Kyrgyz–Tajik border',
                publisher: 'President of the Kyrgyz Republic',
                publishedAt: '2025-03-13',
                url: 'https://president.kg/ru/news/21/38920',
                perspectiveType: 'local',
                perspective: 'Official Kyrgyz account of reopening border crossings after the agreement',
                supports: 'An early implementation measure intended to restore movement and bilateral contact',
            },
            {
                title: 'Women leaders build interethnic cohesion in border communities of Kyrgyzstan',
                publisher: 'United Nations Sustainable Development Group',
                publishedAt: '2026-01-19',
                url: 'https://unsdg.un.org/latest/stories/women-leaders-build-interethnic-cohesion-border-communities-kyrgyzstan',
                perspectiveType: 'institutional',
                perspective: 'UN community-peacebuilding and social-inclusion lens',
                supports: 'The importance of women\'s leadership, local trust, and resource-pressure management after conflict',
            },
            {
                title: 'Central Asian States Have Put Aside Their Territorial Disputes. Why Now?',
                publisher: 'Carnegie Endowment for International Peace',
                publishedAt: '2025-04-09',
                url: 'https://carnegieendowment.org/russia-eurasia/politika/2025/04/kyrgyzstan-tajikistan-border-deal',
                perspectiveType: 'independent',
                perspective: 'Independent Central Asian analysis of the settlement\'s incentives and constraints',
                supports: 'Regional diplomacy, domestic trade-offs, and reasons implementation may still face setbacks',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'A State-Level Settlement',
                perspectiveLabel: 'National governments',
                perspectiveType: 'local',
                narration: 'The treaty and reopened crossings demonstrate a shift from recurring territorial confrontation toward negotiated implementation.',
                focusQuestion: 'Which practical measures make a signed border agreement credible to people who live beside it?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'The Border-Community Test',
                perspectiveLabel: 'Local communities',
                perspectiveType: 'local',
                narration: 'Everyday peace depends on safe movement and workable access to homes, markets, land, and water, not only an agreed line on a map.',
                focusQuestion: 'How should governments resolve local losses or access disputes created by a national compromise?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Inclusive Peacebuilding',
                perspectiveLabel: 'Women peacebuilders and UN partners',
                perspectiveType: 'institutional',
                narration: 'UN reporting highlights women-led dialogue and interethnic cooperation as mechanisms for rebuilding trust after violence.',
                focusQuestion: 'Whose participation is essential if formal peace is to become socially durable?',
            },
            {
                nodeId: 'Russia',
                title: 'A Changing Regional System',
                perspectiveLabel: 'Independent regional analysis',
                perspectiveType: 'independent',
                narration: 'The settlement reflects new incentives for Central Asian cooperation within a regional order historically shaped by Soviet borders and Russian influence.',
                focusQuestion: 'Did changing external relationships make compromise more valuable than continued territorial rivalry?',
            },
        ],
    },
    {
        id: 'mongolia-coal-critical-minerals-transition',
        title: 'Mongolia Between Coal and Critical Minerals',
        subtitle: 'Resource dependence, public benefit, and a just energy transition',
        regionTags: ['Asia-Pacific', 'East Asia', 'Mongolia'],
        coverageRegion: 'East Asia',
        issueDimensions: ['Critical minerals', 'Coal dependence', 'Benefit sharing', 'Just transition'],
        actors: ['Government of Mongolia', 'Mongolian mining communities', 'Chinese buyers and investors', 'Russian energy suppliers', 'UNDP'],
        nexusNodeIds: ['AsiaPacific', 'China', 'Russia', 'UN_OPEC'],
        statusSummary: 'Mongolia adopted a Just Energy Transition Framework in December 2025 while continuing to rely heavily on mining and coal. In May 2026, the government presented reforms intended to direct more value from strategic deposits to citizens, while independent Mongolian analysis argued that the strategic-deposit framework still creates governance and investment tensions.',
        whyItMatters: 'Mongolia must seek public value from mineral demand and improve energy security without allowing export concentration, coal dependence, or unstable rules to narrow its development options.',
        updatedAt: '2026-05-11',
        confidence: 'medium',
        uncertainty: 'Government benefit-sharing proposals may change during implementation, investment outcomes remain uncertain, and the pace of coal and power-sector transition depends on infrastructure and external demand.',
        coordinates: { latitude: 47.8864, longitude: 106.9057 },
        broadCategory: 'Climate, Resources & Security',
        featured: true,
        sensitivity: 'standard',
        reviewCadenceDays: 45,
        reviewBy: '2026-09-23',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Ulaanbaatar', latitude: 47.8864, longitude: 106.9057 },
                { label: 'Oyu Tolgoi', latitude: 43.008, longitude: 106.843 },
                { label: 'Sainshand', latitude: 44.89, longitude: 110.136 },
                { label: 'Zamyn-Uud', latitude: 43.715, longitude: 111.904 },
            ],
        },
        sources: [
            {
                title: 'Strategic-deposit reforms create an opportunity to increase benefits for citizens',
                publisher: 'Government of Mongolia',
                publishedAt: '2026-05-11',
                url: 'https://mongolia.gov.mn/news/view/27582',
                perspectiveType: 'local',
                perspective: 'Official Mongolian resource-benefit and ownership policy',
                supports: 'The government\'s stated effort to direct more strategic-deposit value to the public',
            },
            {
                title: 'Just Energy Transition Framework',
                publisher: 'United Nations Development Programme Mongolia',
                publishedAt: '2025-12-16',
                url: 'https://www.undp.org/mongolia/publications/just-energy-transition-framework',
                perspectiveType: 'institutional',
                perspective: 'UNDP and national-policy framework for an inclusive energy transition',
                supports: 'Coal dependence, energy-system reform, social inclusion, and sequencing of transition policies',
            },
            {
                title: 'Mongolia\'s Strategic Deposits: A Framework Under Strain in the Critical Minerals Race',
                publisher: 'Think Mongol Institute',
                publishedAt: '2026-05-07',
                url: 'https://thinkmongol.mn/en/post/policybrief-7',
                perspectiveType: 'independent',
                perspective: 'Independent Mongolian analysis of minerals governance and investment risk',
                supports: 'Tensions between strategic control, predictable rules, investment, and long-term public value',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'Who Benefits From the Resource Base?',
                perspectiveLabel: 'Mongolian public policy',
                perspectiveType: 'local',
                narration: 'The government frames strategic-deposit reform as a route to broader citizen benefit, while implementation will determine how ownership translates into durable public value.',
                focusQuestion: 'Which institutions can turn volatile mining revenue into transparent, long-term public benefit?',
            },
            {
                nodeId: 'China',
                title: 'The Export-Concentration Constraint',
                perspectiveLabel: 'Trade and investment system',
                perspectiveType: 'independent',
                narration: 'Geography makes access to Chinese markets central to Mongolia\'s mineral economy, increasing both opportunity and exposure to concentrated demand.',
                focusQuestion: 'How much diversification is economically realistic for a landlocked mineral exporter?',
            },
            {
                nodeId: 'Russia',
                title: 'Energy Security During Transition',
                perspectiveLabel: 'Regional energy dependence',
                perspectiveType: 'independent',
                narration: 'A transition away from coal must also account for grid reliability and energy links shaped by Mongolia\'s two large neighbors.',
                focusQuestion: 'What sequence of investment reduces emissions without creating a new form of external dependence?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'A Just Transition Test',
                perspectiveLabel: 'UNDP transition framework',
                perspectiveType: 'institutional',
                narration: 'The transition framework emphasizes policy reform, consultation, and protection for people and places tied to the existing energy economy.',
                focusQuestion: 'How should transition policy distribute near-term costs and future gains across regions and generations?',
            },
        ],
    },
    {
        id: 'indonesia-nickel-development-bargain',
        title: 'Indonesia\'s Nickel Bargain',
        subtitle: 'Industrial upgrading, trade rules, local livelihoods, and environmental standards',
        regionTags: ['Asia-Pacific', 'Southeast Asia', 'Indonesia'],
        coverageRegion: 'Southeast Asia',
        issueDimensions: ['Critical minerals', 'Industrial policy', 'Trade law', 'Labor and environmental standards'],
        actors: ['Government of Indonesia', 'Nickel-region communities and workers', 'Chinese-linked processors and investors', 'European Union', 'World Trade Organization'],
        nexusNodeIds: ['AsiaPacific', 'China', 'Europe', 'TechAIHub'],
        statusSummary: 'Indonesia\'s government continued in 2026 to present mineral downstreaming as a core investment and industrial policy. The WTO dispute record shows that a panel found challenged nickel measures inconsistent with trade rules and that Indonesia appealed into a non-operational appellate system. Independent analysis argues that lasting competitiveness also depends on local skills, community benefit, and stronger labor and environmental performance.',
        whyItMatters: 'Indonesia is testing whether control over a strategic mineral can create broad-based industrial development while meeting trade obligations and protecting communities and ecosystems near extraction and processing sites.',
        updatedAt: '2026-07-17',
        confidence: 'high',
        uncertainty: 'Investment announcements do not by themselves establish local welfare or environmental outcomes. The WTO appeal remains procedurally unresolved, and conditions vary across mining regions and firms.',
        coordinates: { latitude: -2.996, longitude: 121.948 },
        broadCategory: 'Technology & Economics',
        featured: true,
        sensitivity: 'high',
        reviewCadenceDays: 30,
        reviewBy: '2026-09-08',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Jakarta', latitude: -6.2088, longitude: 106.8456 },
                { label: 'Morowali', latitude: -2.996, longitude: 121.948 },
                { label: 'Weda Bay', latitude: 0.474, longitude: 127.955 },
                { label: 'Raja Ampat', latitude: -0.234, longitude: 130.516 },
            ],
        },
        sources: [
            {
                title: 'Investment Realization Reaches IDR 1,010.6 Trillion in the First Half of 2026, Creating 1.4 Million Jobs',
                publisher: 'Ministry of Investment and Downstreaming, Republic of Indonesia',
                publishedAt: '2026-07-17',
                url: 'https://www.bkpm.go.id/en/info/press-release/investment-realization-reaches-idr-1-010-6-trillion-in-the-first-half-of-2026-creating-1-4-million-jobs',
                perspectiveType: 'local',
                perspective: 'Official Indonesian investment and downstreaming account',
                supports: 'The government\'s framing of downstream mineral processing as an industrial-development priority',
            },
            {
                title: 'DS592: Indonesia — Measures Relating to Raw Materials',
                publisher: 'World Trade Organization',
                publishedAt: '2022-12-08',
                url: 'https://www.wto.org/english/tratop_e/dispu_e/cases_e/ds592_e.htm',
                perspectiveType: 'institutional',
                perspective: 'WTO Secretariat procedural and legal summary of the dispute',
                supports: 'The panel findings, Indonesia\'s appeal, and the dispute\'s unresolved procedural status',
            },
            {
                title: 'Indonesia: The downstreaming dilemma',
                publisher: 'Lowy Institute',
                publishedAt: '2025-01-20',
                url: 'https://www.lowyinstitute.org/the-interpreter/indonesia-downstreaming-dilemma',
                perspectiveType: 'independent',
                perspective: 'Independent development analysis incorporating community and labor concerns',
                supports: 'Trade-offs among value addition, skills, local livelihoods, environmental performance, and market access',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'The Downstreaming Strategy',
                perspectiveLabel: 'Indonesian industrial policy',
                perspectiveType: 'local',
                narration: 'Indonesia uses restrictions and domestic-processing requirements to retain more mineral value and build industries beyond raw-ore extraction.',
                focusQuestion: 'What evidence would show that downstreaming is creating durable national capability rather than a temporary investment surge?',
            },
            {
                nodeId: 'China',
                title: 'Capital, Technology, and Dependence',
                perspectiveLabel: 'Investor and supply-chain lens',
                perspectiveType: 'independent',
                narration: 'Chinese-linked investment has accelerated processing capacity, while concentration in ownership, technology, or markets can create new dependencies.',
                focusQuestion: 'How can Indonesia capture expertise and bargaining power as well as investment?',
            },
            {
                nodeId: 'Europe',
                title: 'A Trade-Rules Challenge',
                perspectiveLabel: 'WTO and market-access lens',
                perspectiveType: 'institutional',
                narration: 'The WTO panel rejected Indonesia\'s defense of the challenged measures, but the appeal remains unresolved because of the appellate impasse.',
                focusQuestion: 'How should trade rules accommodate a developing state\'s effort to move up a strategic supply chain?',
            },
            {
                nodeId: 'TechAIHub',
                title: 'The Community and Standards Test',
                perspectiveLabel: 'Workers and nickel-region communities',
                perspectiveType: 'independent',
                narration: 'Local support and access to demanding technology markets depend on skills, safer work, environmental performance, and benefits that reach nearby communities.',
                focusQuestion: 'Which safeguards make battery-mineral growth compatible with local livelihoods and credible clean-technology claims?',
            },
        ],
    },
    {
        id: 'mekong-energy-food-bargain',
        title: 'The Mekong Energy–Food Bargain',
        subtitle: 'Hydropower, fisheries, sediment, and the search for basin-wide evidence',
        regionTags: ['Asia-Pacific', 'Southeast Asia', 'Mekong Basin'],
        coverageRegion: 'Southeast Asia',
        issueDimensions: ['Hydropower', 'Food systems', 'Transboundary water', 'Climate adaptation'],
        actors: ['Lower Mekong governments', 'China', 'Mekong River Commission', 'River communities', 'Energy planners'],
        nexusNodeIds: ['AsiaPacific', 'China', 'UN_OPEC', 'TechAIHub'],
        statusSummary: 'The Mekong River Commission published a joint environmental monitoring plan for the Xayaburi and Don Sahong mainstream dams in September 2025. Vietnam, chairing the MRC Council in 2026, called for stronger data sharing, monitoring, and coordination on hydropower and sediment. Independent analysis points to renewable alternatives that could reduce pressure on river ecology while meeting electricity needs.',
        whyItMatters: 'Electricity choices made in one part of the basin affect fisheries, farms, sediment, flood resilience, and livelihoods elsewhere, making shared evidence and distributional fairness central to energy planning.',
        updatedAt: '2025-11-27',
        confidence: 'high',
        uncertainty: 'Ecological effects are cumulative and difficult to attribute to a single dam. Monitoring plans show institutional intent, but public data quality, implementation, and government responses require continuing review.',
        coordinates: { latitude: 14.5, longitude: 105.5 },
        broadCategory: 'Climate, Resources & Security',
        featured: true,
        sensitivity: 'standard',
        reviewCadenceDays: 45,
        reviewBy: '2026-09-23',
        map: {
            mode: 'route',
            locations: [
                { label: 'Vientiane', latitude: 17.9757, longitude: 102.6331 },
                { label: 'Xayaburi', latitude: 19.25, longitude: 101.75 },
                { label: 'Tonle Sap', latitude: 12.876, longitude: 104.067 },
                { label: 'Can Tho and the Mekong Delta', latitude: 10.0452, longitude: 105.7469 },
            ],
        },
        sources: [
            {
                title: 'Viet Nam to Chair the Mekong River Commission Council in 2026',
                publisher: 'Ministry of Agriculture and Environment, Viet Nam',
                publishedAt: '2025-11-27',
                url: 'https://en.mae.gov.vn/Pages/chi-tiet-tin-Eng.aspx?ItemID=9133',
                perspectiveType: 'local',
                perspective: 'Vietnamese government and downstream-state priorities for the 2026 MRC chairmanship',
                supports: 'Calls for data sharing, basin monitoring, and coordination on hydropower and sediment',
            },
            {
                title: 'An inception report on piloting a Joint Environmental Monitoring Programme on two Mekong Mainstream Dams',
                publisher: 'Mekong River Commission',
                publishedAt: '2025-09-03',
                url: 'https://www.mrcmekong.org/publications/an-inception-report-on-piloting-a-joint-environmental-monitoring-programme-on-two-mekong-mainstream-dams-don-sahong-hydropower-project-and-xayaburi-hydropower-project-6/',
                perspectiveType: 'institutional',
                perspective: 'Intergovernmental basin-monitoring framework',
                supports: 'Planned joint monitoring of hydrology, sediment, water quality, ecology, and fisheries',
            },
            {
                title: 'Balancing Energy and Ecology: Floating Solar in the 3S River Basin',
                publisher: 'Stimson Center',
                publishedAt: '2025-02-24',
                url: 'https://www.stimson.org/2025/balancing-energy-and-ecology-floating-solar-in-the-3s-river-basin/',
                perspectiveType: 'independent',
                perspective: 'Independent regional energy-policy analysis',
                supports: 'Renewable alternatives and trade-offs between electricity security and river ecology',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'Electricity and Development',
                perspectiveLabel: 'Lower Mekong energy planners',
                perspectiveType: 'local',
                narration: 'Hydropower offers electricity and revenue, especially for states seeking export earnings and wider access to power.',
                focusQuestion: 'How should regional planning compare immediate electricity gains with long-term basin costs?',
            },
            {
                nodeId: 'China',
                title: 'The Upstream Data Question',
                perspectiveLabel: 'Whole-basin coordination',
                perspectiveType: 'institutional',
                narration: 'The river system extends beyond the MRC\'s four member countries, so useful forecasting depends on broader hydrological information and cooperation.',
                focusQuestion: 'What information should every upstream operator share during droughts, floods, and rapid flow changes?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Can Shared Monitoring Build Trust?',
                perspectiveLabel: 'Mekong River Commission',
                perspectiveType: 'institutional',
                narration: 'Joint monitoring can create a common evidence base across hydrology, sediment, ecology, water quality, and fisheries, but only if results guide decisions.',
                focusQuestion: 'What makes shared technical data politically consequential rather than merely descriptive?',
            },
            {
                nodeId: 'TechAIHub',
                title: 'Alternatives to a Dam-First Path',
                perspectiveLabel: 'Independent energy analysis',
                perspectiveType: 'independent',
                narration: 'Floating solar and other system-level options can be evaluated alongside hydropower rather than treating each dam as an isolated project.',
                focusQuestion: 'Which mix of generation, storage, grids, and demand management best protects both reliability and river livelihoods?',
            },
        ],
    },
    {
        id: 'pacific-seabed-governance',
        title: 'Who Governs the Pacific Seabed?',
        subtitle: 'Critical minerals, ocean stewardship, and rules for an uncertain industry',
        regionTags: ['Asia-Pacific', 'Pacific Islands', 'Clarion–Clipperton Zone'],
        coverageRegion: 'Pacific',
        issueDimensions: ['Ocean governance', 'Critical minerals', 'Marine biodiversity', 'Small-state development'],
        actors: ['Pacific Island governments and communities', 'Nauru', 'International Seabed Authority', 'Mining contractors', 'Marine scientists'],
        nexusNodeIds: ['AsiaPacific', 'UN_OPEC', 'TechAIHub'],
        statusSummary: 'The International Seabed Authority continued negotiating exploitation regulations and associated safeguards in July 2026, with important issues still listed for further work. Nauru continues to present sponsored seabed development as a route to participation in the energy transition and national benefit, while independent research finds that physical and biological effects remained visible decades after a historic collector test.',
        whyItMatters: 'The case asks who should decide how minerals beyond national jurisdiction are used, how uncertain ecological losses should be valued, and whether small island states can gain development agency without carrying disproportionate ocean risk.',
        updatedAt: '2026-07-24',
        confidence: 'high',
        uncertainty: 'The mining code is still under negotiation, commercial authorization is not established by the cited session record, and evidence from historic or test-scale disturbance does not fully predict modern commercial-scale effects.',
        coordinates: { latitude: 12, longitude: -135 },
        broadCategory: 'Climate, Resources & Security',
        featured: true,
        sensitivity: 'high',
        reviewCadenceDays: 14,
        reviewBy: '2026-08-23',
        map: {
            mode: 'global',
            locations: [
                { label: 'Kingston — International Seabed Authority', latitude: 17.9712, longitude: -76.7936 },
                { label: 'Nauru', latitude: -0.5228, longitude: 166.9315 },
                { label: 'Suva — regional Pacific diplomacy', latitude: -18.1248, longitude: 178.4501 },
                { label: 'Clarion–Clipperton Zone', latitude: 12, longitude: -135 },
            ],
        },
        sources: [
            {
                title: 'Nauru and TMC sign updated sponsorship agreement',
                publisher: 'Government of the Republic of Nauru',
                publishedAt: '2025-06-06',
                url: 'https://www.nauru.gov.nr/government-information-office/media-release/media-release-nauru%2C-tmc-sign-new-agreement_6jun2025.aspx',
                perspectiveType: 'local',
                perspective: 'Official Nauruan development, stewardship, and sponsor-state position',
                supports: 'Nauru\'s stated rationale for sponsored mineral development and expected national participation',
            },
            {
                title: '31st Session of the Council, Part II: 13–24 July 2026',
                publisher: 'International Seabed Authority',
                publishedAt: '2026-07-24',
                url: 'https://isa.org.jm/session-31-council-part-2-july-2026/',
                perspectiveType: 'institutional',
                perspective: 'Multilateral negotiation record for rules governing mineral exploitation in the international seabed area',
                supports: 'The revised regulatory text, environmental proposals, and issues still under negotiation',
            },
            {
                title: 'Long-term impact and biological recovery in a deep-sea mining track',
                publisher: 'Nature',
                publishedAt: '2025-03-26',
                url: 'https://www.nature.com/articles/s41586-025-08921-3',
                perspectiveType: 'independent',
                perspective: 'Peer-reviewed independent evidence on ecological recovery after seabed disturbance',
                supports: 'Persistent physical and biological effects, partial recolonization, and the limits of current evidence',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'A Small-State Development Claim',
                perspectiveLabel: 'Nauruan sponsor-state position',
                perspectiveType: 'local',
                narration: 'Nauru frames sponsored seabed development as a way for a small island state to participate in critical-mineral value chains while exercising ocean stewardship.',
                focusQuestion: 'What safeguards and benefit terms would make that development claim credible to Nauruan and wider Pacific publics?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'The Precautionary Pacific View',
                perspectiveLabel: 'Ocean-dependent communities',
                perspectiveType: 'independent',
                narration: 'For communities whose economies, cultures, and security are tied to the ocean, scientific uncertainty can itself be a reason to demand caution and meaningful consent.',
                focusQuestion: 'Who bears the burden of proof when damage may be difficult to observe, reverse, or compensate?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Rules for the Common Heritage',
                perspectiveLabel: 'International Seabed Authority',
                perspectiveType: 'institutional',
                narration: 'The ISA is still negotiating environmental management, compliance, payment, and other core rules rather than presenting a finished exploitation regime.',
                focusQuestion: 'What must be resolved before a multilateral regulator can make a legitimate decision on commercial extraction?',
            },
            {
                nodeId: 'TechAIHub',
                title: 'Mineral Demand Meets Ecological Uncertainty',
                perspectiveLabel: 'Science and technology systems',
                perspectiveType: 'independent',
                narration: 'Critical-mineral demand creates pressure to expand supply, while peer-reviewed evidence shows that some disturbances remain visible and communities remain altered decades later.',
                focusQuestion: 'Should uncertain seabed supply be compared with demand reduction, recycling, substitution, and improved land-mining standards?',
            },
        ],
    },
];
