/**
 * Auditable 2026 case studies for the forecast feed and Guided Briefings.
 *
 * Current-status claims are deliberately attributed to the official sources
 * attached to each record. Analytical prompts are framed as questions rather
 * than predictions.
 */
export const CASE_STUDIES_2026 = [
    {
        id: 'sudan-displacement-regional-spillover',
        title: 'Sudan: War, Displacement, and Regional Spillover',
        subtitle: 'How a civil war became the world\'s largest displacement crisis',
        regionTags: ['Africa', 'Horn of Africa', 'Sahel'],
        issueDimensions: ['Armed conflict', 'Forced displacement', 'Humanitarian access', 'Regional security'],
        actors: ['Sudanese Armed Forces', 'Rapid Support Forces', 'Sudanese civilians', 'Neighboring host states', 'UNHCR'],
        nexusNodeIds: ['Africa', 'MilitantPMC', 'UN_OPEC'],
        statusSummary: 'On 10 April 2026, UNHCR reported that fighting was continuing into the war\'s fourth year and that roughly 14 million people had been forced to flee since April 2023, including about 9 million displaced inside Sudan and 4.4 million across borders.',
        whyItMatters: 'The case connects state fragmentation, paramilitary power, civilian protection, regional burden-sharing, and the limits of international humanitarian response.',
        updatedAt: '2026-04-10',
        confidence: 'high',
        uncertainty: 'Displacement totals, humanitarian access, funding, and territorial control change quickly and should be rechecked against UNHCR operational data before each editorial update.',
        coordinates: { latitude: 15.5007, longitude: 32.5599 },
        broadCategory: 'Geopolitics & Conflict',
        sources: [
            {
                title: 'Three years on, war-weary Sudanese remain on the move',
                publisher: 'UNHCR',
                publishedAt: '2026-04-10',
                url: 'https://www.unhcr.org/news/briefing-notes/three-years-war-weary-sudanese-remain-move',
                perspective: 'United Nations humanitarian and displacement reporting',
            },
        ],
        waypoints: [
            {
                nodeId: 'Africa',
                title: 'A War Without an Endpoint',
                narration: 'UNHCR reported in April 2026 that fighting was still continuing as the conflict entered its fourth year.',
                focusQuestion: 'What prevents military pressure from becoming a durable political settlement?',
            },
            {
                nodeId: 'MilitantPMC',
                title: 'State and Paramilitary Power',
                narration: 'The conflict pits the Sudanese Armed Forces against the paramilitary Rapid Support Forces, while civilians absorb the central protection costs.',
                focusQuestion: 'How does a powerful paramilitary organization alter conventional ideas of sovereignty?',
            },
            {
                nodeId: 'Africa',
                title: 'Displacement Across Borders',
                narration: 'UNHCR counted about 9 million people displaced inside Sudan and 4.4 million across borders by April 2026.',
                focusQuestion: 'When does a domestic conflict become a regional security and development crisis?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'A Response Under Strain',
                narration: 'UNHCR described major funding gaps for both assistance inside Sudan and the regional refugee response.',
                focusQuestion: 'What obligations should outside states accept when humanitarian need greatly exceeds available funding?',
            },
        ],
    },
    {
        id: 'myanmar-fragmented-sovereignty',
        title: 'Myanmar: Fragmented Sovereignty and Humanitarian Access',
        subtitle: 'Conflict, displacement, and the struggle to reach civilians',
        regionTags: ['Asia', 'Southeast Asia'],
        issueDimensions: ['Contested sovereignty', 'Armed conflict', 'Humanitarian access', 'Displacement'],
        actors: ['Myanmar military authorities', 'Resistance organizations', 'Ethnic armed organizations', 'Myanmar civilians', 'OCHA and humanitarian partners'],
        nexusNodeIds: ['AsiaPacific', 'UN_OPEC'],
        statusSummary: 'OCHA reported on 13 July 2026 that more than 16 million people needed humanitarian assistance and nearly 3.8 million were displaced, while conflict, movement restrictions, and administrative requirements continued to obstruct aid access.',
        whyItMatters: 'Myanmar shows how competing claims to authority, territorial fragmentation, and restricted humanitarian access can weaken both domestic governance and regional diplomacy.',
        updatedAt: '2026-07-13',
        confidence: 'high',
        uncertainty: 'Access constraints limit independent observation, so casualty counts, local control, and new displacement estimates require cautious attribution and frequent updates.',
        coordinates: { latitude: 19.7633, longitude: 96.0785 },
        broadCategory: 'Geopolitics & Conflict',
        sources: [
            {
                title: 'Myanmar Humanitarian Update No. 52',
                publisher: 'OCHA / United Nations in Myanmar',
                publishedAt: '2026-07-13',
                url: 'https://myanmar.un.org/en/319232-myanmar-humanitarian-update-no-52',
                perspective: 'United Nations humanitarian situation and response reporting',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'A Nationwide Humanitarian Crisis',
                narration: 'OCHA estimated that more than 16 million people needed assistance across Myanmar in July 2026.',
                focusQuestion: 'What does widespread humanitarian need reveal about the state\'s capacity and legitimacy?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'Repeated Displacement',
                narration: 'Nearly 3.8 million people were estimated to be displaced, with renewed fighting continuing to force new movements.',
                focusQuestion: 'How does repeated displacement change communities\' political and economic choices?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Blocked Humanitarian Reach',
                narration: 'OCHA identified hostilities, movement restrictions, and administrative requirements as continuing barriers to aid.',
                focusQuestion: 'How can humanitarian actors remain neutral while negotiating access with competing authorities?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'The Response Gap',
                narration: 'By the end of March, partners had reached 1.6 million people, while the 2026 response was 43 percent funded in the July update.',
                focusQuestion: 'How should scarce assistance be prioritized when the target population cannot all be reached?',
            },
        ],
    },
    {
        id: 'south-china-sea-arbitral-award-ten-years',
        title: 'South China Sea: Ten Years After the Arbitral Award',
        subtitle: 'International law, competing state positions, and maritime order',
        regionTags: ['Asia-Pacific', 'Southeast Asia', 'South China Sea'],
        issueDimensions: ['Maritime entitlements', 'International law', 'Dispute settlement', 'Regional security'],
        actors: ['Philippines', 'China', 'Annex VII arbitral tribunal', 'Southeast Asian coastal states'],
        nexusNodeIds: ['AsiaPacific', 'China', 'UN_OPEC'],
        statusSummary: 'Ten years after the 2016 award, the Philippine government continues to present it as a final and binding guide to maritime rights under UNCLOS, while China\'s government continues to reject the arbitration and award as invalid. These are attributed government positions; the underlying award addressed maritime entitlements and conduct, not sovereignty over land territory or boundary delimitation.',
        whyItMatters: 'The dispute offers a direct test of the relationship between formal legal decisions, state consent, material power, and peaceful management of competing maritime claims.',
        updatedAt: '2026-07-21',
        confidence: 'high',
        uncertainty: 'Official descriptions of incidents and legal meaning are contested. Each state claim should remain attributed, and operational developments at sea require separate, incident-specific verification.',
        coordinates: { latitude: 12, longitude: 114 },
        broadCategory: 'Geopolitics & Conflict',
        sources: [
            {
                title: 'The South China Sea Arbitration: Award of 12 July 2016',
                publisher: 'Permanent Court of Arbitration (registry)',
                publishedAt: '2016-07-12',
                url: 'https://docs.pca-cpa.org/2016/07/PH-CN-20160712-Award.pdf',
                perspective: 'Official text of the Annex VII arbitral tribunal award',
            },
            {
                title: 'Delhi Roundtable Accentuates Abiding Relevance of South China Sea Arbitral Award on Decennial',
                publisher: 'Department of Foreign Affairs of the Philippines',
                publishedAt: '2026-07-21',
                url: 'https://newdelhipe.dfa.gov.ph/index.php/newsroom/embassy-news/1230-delhi-roundtable-accentuates-abiding-relevance-of-south-china-sea-arbitral-award-on-decennial',
                perspective: 'Official Philippine government position supporting the award',
            },
            {
                title: 'Foreign Ministry Spokesperson Lin Jian\'s Regular Press Conference on July 14, 2026',
                publisher: 'Ministry of Foreign Affairs of the People\'s Republic of China',
                publishedAt: '2026-07-14',
                url: 'https://www.mfa.gov.cn/eng/xw/fyrbt/202607/t20260714_11982116.html',
                perspective: 'Official Chinese government position rejecting the arbitration and award',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'What the Tribunal Decided',
                narration: 'The tribunal addressed maritime entitlements and conduct under UNCLOS; it did not decide sovereignty over land territory or delimit a maritime boundary.',
                focusQuestion: 'Why does the legal scope of a ruling matter as much as its outcome?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Law as a Dispute Mechanism',
                narration: 'The 2016 award supplies a formal legal record against which later state arguments and conduct can be evaluated.',
                focusQuestion: 'What gives an international legal decision influence when enforcement is decentralized?',
            },
            {
                nodeId: 'China',
                title: 'China\'s Rejection',
                narration: 'China\'s Foreign Ministry says the tribunal lacked authority and that disputes should be handled through negotiation by the parties concerned.',
                focusQuestion: 'How does state consent shape the legitimacy of international adjudication?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'The Philippine Position',
                narration: 'The Philippine government treats the award as final, binding, and central to a rules-based maritime order.',
                focusQuestion: 'How can a smaller state use legal institutions to offset an asymmetry in material power?',
            },
        ],
    },
    {
        id: 'syria-transition-return-sanctions',
        title: 'Syria: Political Transition, Return, and Sanctions Relief',
        subtitle: 'Large-scale return inside a still-fragile recovery system',
        regionTags: ['Middle East', 'Levant'],
        issueDimensions: ['Political transition', 'Refugee return', 'Sanctions', 'Reconstruction'],
        actors: ['Syrian transitional authorities', 'Syrian refugees and internally displaced people', 'UNHCR', 'European Union', 'Neighboring host states'],
        nexusNodeIds: ['MiddleEast', 'Europe', 'UN_OPEC'],
        statusSummary: 'UNHCR reported in March 2026 that 15.6 million people required assistance and that more than 1.5 million refugees and 1.8 million internally displaced people had returned since December 2024. In May 2026, the EU renewed targeted measures against former-regime networks while describing broad economic sanctions as having been lifted in 2025 to support transition and recovery.',
        whyItMatters: 'Syria tests whether political transition and sanctions relief can produce voluntary, safe, and sustainable return before housing, services, livelihoods, documentation, and accountable institutions have recovered.',
        updatedAt: '2026-05-18',
        confidence: 'high',
        uncertainty: 'Return totals change frequently and conditions vary sharply by locality. A recorded return must not be treated as proof that return was safe, voluntary, or sustainable.',
        coordinates: { latitude: 33.5138, longitude: 36.2765 },
        broadCategory: 'Geopolitics & Conflict',
        sources: [
            {
                title: 'Operational Update – Syria, March 2026',
                publisher: 'UNHCR',
                publishedAt: '2026-03',
                url: 'https://www.unhcr.org/sites/default/files/2026-04/unhcr-syria-operational-update-march.pdf',
                perspective: 'United Nations protection, return, and humanitarian reporting',
            },
            {
                title: 'Syria: Council renews restrictive measures targeting the former al-Assad regime for one year and de-lists certain entities',
                publisher: 'Council of the European Union',
                publishedAt: '2026-05-18',
                url: 'https://www.consilium.europa.eu/en/press/press-releases/2026/05/18/syria-council-renews-restrictive-measures-targeting-the-former-al-assad-regime-for-one-year-and-de-lists-certain-entities/',
                perspective: 'Official European Union sanctions and engagement policy',
            },
        ],
        waypoints: [
            {
                nodeId: 'MiddleEast',
                title: 'A Changed Political Context',
                narration: 'UNHCR describes a post-December 2024 environment in which political change and large-scale returns coexist with severe humanitarian need.',
                focusQuestion: 'When does a change in government become a durable political transition?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Return at Scale',
                narration: 'By March 2026, UNHCR counted more than 1.5 million refugee returns and 1.8 million returns by internally displaced people since December 2024.',
                focusQuestion: 'Which indicators show whether a return is sustainable rather than temporary?',
            },
            {
                nodeId: 'Europe',
                title: 'Sanctions Recalibrated',
                narration: 'The EU says broad economic sanctions were lifted to support transition and recovery while targeted measures against former-regime networks remain.',
                focusQuestion: 'Can targeted sanctions preserve accountability without obstructing wider recovery?',
            },
            {
                nodeId: 'MiddleEast',
                title: 'The Reintegration Test',
                narration: 'UNHCR identifies damaged housing, limited services and livelihoods, documentation needs, and local capacity as constraints on sustainable return.',
                focusQuestion: 'Who should bear the cost and responsibility for rebuilding the conditions needed for return?',
            },
        ],
    },
    {
        id: 'guyana-venezuela-essequibo-icj',
        title: 'Guyana–Venezuela: Essequibo Before the ICJ',
        subtitle: 'A territorial controversy moves through international adjudication',
        regionTags: ['Latin America', 'Caribbean', 'Northern South America'],
        issueDimensions: ['Territorial sovereignty', 'International adjudication', 'Regional diplomacy', 'Peaceful dispute settlement'],
        actors: ['Guyana', 'Venezuela', 'International Court of Justice', 'CARICOM'],
        nexusNodeIds: ['LatinAmerica', 'UN_OPEC'],
        statusSummary: 'CARICOM reported that the International Court of Justice held merits hearings from 4 to 11 May 2026 and continues to support Guyana and the judicial process. Venezuela\'s Foreign Ministry says it does not recognize the Court\'s jurisdiction in this matter and presents the 1966 Geneva Agreement as the valid route to resolution. The Court\'s merits judgment remains pending.',
        whyItMatters: 'The case tests whether international adjudication and regional diplomacy can manage a high-stakes territorial controversy without coercive alteration of the status quo.',
        updatedAt: '2026-07-10',
        confidence: 'high',
        uncertainty: 'The merits judgment is pending and no outcome should be forecast. CARICOM\'s support for Guyana and Venezuela\'s jurisdictional objection are attributed policy positions, not substitutes for the Court\'s eventual findings.',
        coordinates: { latitude: 6.4, longitude: -59 },
        broadCategory: 'Geopolitics & Conflict',
        sources: [
            {
                title: 'Arbitral Award of 3 October 1899 (Guyana v. Venezuela)',
                publisher: 'International Court of Justice',
                publishedAt: null,
                url: 'https://www.icj-cij.org/case/171',
                perspective: 'Official Court docket and procedural record; the page is updated as the case develops',
            },
            {
                title: 'Communiqué: Fifty-First Regular Meeting of the Conference of Heads of Government of CARICOM',
                publisher: 'Caribbean Community',
                publishedAt: '2026-07-10',
                url: 'https://caricom.org/communique-fifty-first-regular-meeting-of-the-conference-of-heads-of-government-of-the-caribbean-community-caricom-saint-lucia/',
                perspective: 'Official CARICOM proceeding summary and regional policy position supporting Guyana',
            },
            {
                title: 'Venezuela desmontó ante la CIJ argumentos de Guyana y ratifica Acuerdo de Ginebra',
                publisher: 'Ministry of Foreign Affairs of Venezuela',
                publishedAt: '2026-05-06',
                url: 'https://mppre.gob.ve/publicacion/7224-venezuela-desmonto-ante-la-cij-argumentos-de-guyana-y-ratifica-acuerdo-de-ginebra',
                perspective: 'Official Venezuelan position rejecting the Court\'s jurisdiction and prioritizing the 1966 Geneva Agreement',
            },
        ],
        waypoints: [
            {
                nodeId: 'LatinAmerica',
                title: 'A Regional Territorial Controversy',
                narration: 'Guyana pursues adjudication before the International Court of Justice, while Venezuela appeared at the 2026 hearings but maintains that it does not recognize the Court\'s jurisdiction in this matter.',
                focusQuestion: 'Why might states choose adjudication instead of bilateral bargaining?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'The Merits Heard',
                narration: 'CARICOM reported that the Court heard two rounds of oral argument from 4 to 11 May 2026.',
                focusQuestion: 'What can an international court resolve, and what political work remains outside the courtroom?',
            },
            {
                nodeId: 'LatinAmerica',
                title: 'CARICOM\'s Position',
                narration: 'CARICOM supports the judicial process and has explicitly reaffirmed its support for Guyana\'s sovereignty and territorial integrity.',
                focusQuestion: 'How can regional solidarity affect a dispute without deciding its legal merits?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Judgment Pending',
                narration: 'The Court has not yet delivered its merits judgment, so the outcome remains open.',
                focusQuestion: 'What should responsible analysis avoid while a binding judgment is still pending?',
            },
        ],
    },
    {
        id: 'usmca-2026-joint-review',
        title: 'USMCA After the 2026 Joint Review',
        subtitle: 'Integration continues while annual bargaining replaces immediate extension',
        regionTags: ['North America', 'United States', 'Mexico', 'Canada'],
        issueDimensions: ['Regional trade', 'Economic security', 'Industrial policy', 'Supply-chain integration'],
        actors: ['United States', 'Mexico', 'Canada', 'North American workers', 'Manufacturers and agricultural producers'],
        nexusNodeIds: ['USA', 'LatinAmerica'],
        statusSummary: 'The United States declined an immediate 16-year extension at the 1 July 2026 joint review. Official statements from all three countries say the agreement remains in force while negotiations continue; Canadian and Mexican statements specify that it remains in force through 2036 and that annual reviews will continue.',
        whyItMatters: 'USMCA makes it possible to examine how deeply integrated economies use recurring negotiations to balance shared production networks against national industrial and political priorities.',
        updatedAt: '2026-07-23',
        confidence: 'high',
        uncertainty: 'Negotiations remain active and each government frames the review differently. Failure to grant an immediate extension must not be described as termination of the agreement.',
        coordinates: { latitude: 39, longitude: -101 },
        broadCategory: 'Economy & Trade',
        sources: [
            {
                title: 'American Farmers, Ranchers, Manufacturers, and Businesses Applaud President Trump for Not Rubber Stamping the USMCA',
                publisher: 'Office of the United States Trade Representative',
                publishedAt: '2026-07-02',
                url: 'https://www.ustr.gov/about/policy-offices/press-office/press-releases/2026/july/american-farmers-ranchers-manufacturers-and-businesses-applaud-president-trump-not-rubber-stamping',
                perspective: 'Official United States position explaining the decision not to extend immediately',
            },
            {
                title: 'Minister LeBlanc updates provincial and territorial ministers responsible for International Trade on CUSMA Joint Review',
                publisher: 'Global Affairs Canada',
                publishedAt: '2026-07-03',
                url: 'https://www.canada.ca/en/global-affairs/news/2026/07/minister-leblanc-updates-provincial-and-territorial-ministers-responsible-for-international-trade-on-cusma-joint-review.html',
                perspective: 'Official Canadian account emphasizing continuity and Canadian priorities',
            },
            {
                title: 'Quinta Reunión de la Comisión de Libre Comercio del T-MEC: Proceso de Revisión Conjunta previsto en el artículo 34.7',
                publisher: 'Secretaría de Economía de México',
                publishedAt: '2026-07-01',
                url: 'https://www.gob.mx/se/prensa/quinta-reunion-de-la-comision-de-libre-comercio-del-t-mec-proceso-de-revision-conjunta-previsto-en-el-articulo-34-7?idiom=es-MX',
                perspective: 'Official Mexican account of the joint review, continued term, and annual-review process',
            },
            {
                title: 'México mantiene ventaja arancelaria para exportar al mercado estadounidense',
                publisher: 'Secretaría de Economía de México',
                publishedAt: '2026-07-23',
                url: 'https://www.gob.mx/se/prensa/mexico-mantiene-ventaja-arancelaria-para-exportar-al-mercado-estadounidense',
                perspective: 'Official Mexican update on continuing bilateral review negotiations',
            },
        ],
        waypoints: [
            {
                nodeId: 'USA',
                title: 'No Immediate Extension',
                narration: 'USTR says the United States declined to extend USMCA automatically while it seeks changes through further negotiation.',
                focusQuestion: 'When does withholding certainty create useful leverage, and when does it impose excessive cost?',
            },
            {
                nodeId: 'LatinAmerica',
                title: 'The Agreement Continues',
                narration: 'Canadian and Mexican official statements emphasize that USMCA remains in force through 2036 despite the absence of an immediate extension.',
                focusQuestion: 'Why is the distinction between continuation and extension politically important?',
            },
            {
                nodeId: 'USA',
                title: 'Industrial Bargaining',
                narration: 'Official updates describe continuing talks over steel, aluminum, strategic sectors, and regional supply chains.',
                focusQuestion: 'Who gains and who loses when trade rules are redesigned around economic security?',
            },
            {
                nodeId: 'LatinAmerica',
                title: 'Competing National Narratives',
                narration: 'The three governments frame the review differently while agreeing that negotiation and the agreement itself continue.',
                focusQuestion: 'How should analysts separate a government\'s negotiating message from the agreement\'s legal status?',
            },
        ],
    },
    {
        id: 'tuvalu-australia-falepili-union',
        title: 'Tuvalu–Australia Falepili Union',
        subtitle: 'Climate mobility, continuing statehood, and a new security partnership',
        regionTags: ['Pacific', 'Oceania', 'Small Island States'],
        issueDimensions: ['Climate mobility', 'Continuing statehood', 'Adaptation', 'Asymmetric security partnership'],
        actors: ['Tuvalu', 'Australia', 'Tuvaluan citizens'],
        nexusNodeIds: ['AsiaPacific', 'UN_OPEC'],
        statusSummary: 'The Falepili Union entered into force on 28 August 2024. Australia states that the treaty recognizes Tuvalu\'s continuing statehood despite climate-related sea-level rise and creates a permanent-residence mobility pathway with up to 280 places per program year. The 2026 ballot closed on 1 June 2026.',
        whyItMatters: 'The arrangement links climate adaptation, mobility, legal continuity of a threatened state, culture, and security cooperation without treating mobility participants as refugees.',
        updatedAt: '2026-06-01',
        confidence: 'high',
        uncertainty: 'Annual allocations and selection timing can change. The pathway is permanent-residence mobility, not formal refugee recognition, and claims about demographic or brain-drain effects need separate evidence.',
        coordinates: { latitude: -8.5211, longitude: 179.1962 },
        broadCategory: 'Environment & Energy',
        sources: [
            {
                title: 'Australia–Tuvalu Falepili Union treaty',
                publisher: 'Australian Department of Foreign Affairs and Trade',
                publishedAt: null,
                url: 'https://www.dfat.gov.au/geo/tuvalu/australia-tuvalu-falepili-union-treaty',
                perspective: 'Current official Australian treaty and implementation overview; the page does not expose a publication date',
            },
            {
                title: 'Pacific Engagement visa (subclass 192) – Treaty stream ballot registration',
                publisher: 'Australian Department of Home Affairs',
                publishedAt: '2026-04-16',
                url: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/pacific-engagement/subclass-192/treaty-stream/ballot-registration',
                perspective: 'Official eligibility, allocation, and 2026 ballot information',
            },
        ],
        waypoints: [
            {
                nodeId: 'AsiaPacific',
                title: 'Continuing Statehood',
                narration: 'Australia says the treaty legally recognizes Tuvalu\'s continuing statehood and sovereignty despite climate-related sea-level rise.',
                focusQuestion: 'Can statehood remain legally continuous if habitable territory is severely reduced?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'Mobility With Dignity',
                narration: 'The pathway offers permanent residence in Australia to selected Tuvaluan citizens and their eligible families; it is not refugee status.',
                focusQuestion: 'How can mobility policy preserve choice, culture, and connection to home?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'A Limited Annual Pathway',
                narration: 'Australia allocates up to 280 places per program year through a ballot; the 2026 registration period closed on 1 June.',
                focusQuestion: 'What does a fair allocation process look like when demand exceeds available places?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'A Wider Legal Precedent',
                narration: 'The bilateral recognition of continuing statehood raises broader questions for international responses to sea-level rise.',
                focusQuestion: 'Should international law adopt a general rule protecting statehood and maritime rights as seas rise?',
            },
        ],
    },
    {
        id: 'greenland-autonomy-security-minerals',
        title: 'Greenland: Autonomy, Arctic Security, and Critical Minerals',
        subtitle: 'Self-determination inside an increasingly strategic Arctic',
        regionTags: ['Arctic', 'Greenland', 'North Atlantic'],
        issueDimensions: ['Self-determination', 'Arctic security', 'Critical minerals', 'Local participation'],
        actors: ['Government of Greenland', 'Greenlandic public', 'Denmark', 'NATO allies', 'United States and European Union mineral partners'],
        nexusNodeIds: ['Europe', 'USA', 'NATO', 'TechAIHub'],
        statusSummary: 'Greenland\'s government and Denmark announced expanded allied military activity in and around Greenland in January 2026. Greenland\'s Section 21 Commission began work in March on the legal requirements for a possible independence process, while the 2025–2029 mineral strategy prioritizes sustainability, local benefit, critical minerals, and partnerships including with the United States and European Union.',
        whyItMatters: 'Greenland brings self-determination, local consent, alliance security, Arctic strategic change, and competition for critical-mineral supply chains into one case without reducing Greenland to an object of outside strategy.',
        updatedAt: '2026-03-19',
        confidence: 'high',
        uncertainty: 'Security, autonomy, and mineral development are distinct policy tracks. External geopolitical rhetoric changes rapidly, and mineral potential must not be presented as proven commercially recoverable reserves.',
        coordinates: { latitude: 64.1814, longitude: -51.6941 },
        broadCategory: 'Geopolitics & Conflict',
        sources: [
            {
                title: 'The Danish Armed Forces expand their presence and continue exercises in Greenland in close cooperation with allies',
                publisher: 'Naalakkersuisut, Government of Greenland',
                publishedAt: '2026-01-14',
                url: 'https://naalakkersuisut.gl/Nyheder/2026/01/1401_forsvaret?sc_lang=da',
                perspective: 'Official Greenlandic and Danish account of expanded allied security activity',
            },
            {
                title: 'Section 21 Commission constitutes itself and begins its work',
                publisher: 'Naalakkersuisut, Government of Greenland',
                publishedAt: '2026-03-19',
                url: 'https://naalakkersuisut.gl/Nyheder/2026/03/1903_kommission?sc_lang=da',
                perspective: 'Official Greenlandic account of the legal study concerning a possible independence process',
            },
            {
                title: 'Greenland Mineral Resources Strategy 2025–2029',
                publisher: 'Mineral Resources Authority, Government of Greenland',
                publishedAt: '2025-01-31',
                url: 'https://govmin.gl/publications/greenland-mineral-resources-strategy-2025-2029/',
                perspective: 'Official Greenlandic mineral-development strategy',
            },
        ],
        waypoints: [
            {
                nodeId: 'Europe',
                title: 'Local Benefit First',
                narration: 'Greenland\'s mineral strategy places sustainability, community involvement, information, and local benefit alongside investment goals.',
                focusQuestion: 'Who should define the public interest when global demand targets locally governed resources?',
            },
            {
                nodeId: 'TechAIHub',
                title: 'Critical-Mineral Demand',
                narration: 'The strategy treats critical minerals as important to green-transition technologies and international supply chains.',
                focusQuestion: 'Can mineral development support a green transition without reproducing extractive dependency?',
            },
            {
                nodeId: 'USA',
                title: 'External Partnerships',
                narration: 'Greenland\'s strategy records mineral cooperation with the United States and a sustainable-value-chain partnership with the European Union.',
                focusQuestion: 'How can Greenland use competition among partners to increase its own bargaining power?',
            },
            {
                nodeId: 'NATO',
                title: 'A More Strategic Arctic',
                narration: 'Greenland and Denmark announced expanded 2026 exercises with NATO allies, including protection of critical infrastructure and Arctic operations.',
                focusQuestion: 'How can stronger deterrence be reconciled with local participation and a preference for regional stability?',
            },
            {
                nodeId: 'Europe',
                title: 'The Independence Question',
                narration: 'The Section 21 Commission began a legal study in March 2026 of what a process toward an independent Greenland would require.',
                focusQuestion: 'How do economic capacity, security guarantees, and democratic consent shape meaningful self-determination?',
            },
        ],
    },
    {
        id: 'eu-ai-act-transparency-implementation',
        title: 'EU AI Act: Transparency and a Revised Implementation Timeline',
        subtitle: 'AI-generated content rules take effect as high-risk deadlines move',
        regionTags: ['Europe', 'European Union'],
        issueDimensions: ['AI governance', 'Information integrity', 'Regulatory implementation', 'Fundamental rights'],
        actors: ['European Commission and EU AI Office', 'EU member-state authorities', 'AI providers and deployers', 'People interacting with AI systems'],
        nexusNodeIds: ['Europe', 'TechAIHub'],
        statusSummary: 'The EU AI Act reached its general application date on 2 August 2026. Transparency duties now cover specified interactions with AI and the marking or labelling of certain AI-generated or manipulated content. The AI Omnibus, which the European Commission says entered into force on 27 July 2026, moved the main high-risk-system deadline to 2 December 2027 and the deadline for AI embedded in regulated products to 2 August 2028.',
        whyItMatters: 'The case separates political claims about “AI regulation” into concrete duties, voluntary implementation tools, delayed high-risk rules, and questions about whether users can recognize synthetic content in practice.',
        updatedAt: '2026-08-02',
        confidence: 'high',
        uncertainty: 'Implementation guidance, standards, enforcement practice, and the list of code signatories can continue to change. The general application date does not mean every obligation has the same start date, and the voluntary transparency code is not itself the statutory rule.',
        coordinates: { latitude: 50.8503, longitude: 4.3517 },
        broadCategory: 'Technology & Innovation',
        sources: [
            {
                title: 'Regulation (EU) 2024/1689 (Artificial Intelligence Act)',
                publisher: 'EUR-Lex, European Union',
                publishedAt: '2024-07-12',
                url: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj?locale=en',
                perspective: 'Official legal text, including the staged application dates in Article 113',
            },
            {
                title: 'Commission publishes guidelines on transparency obligations for providers and deployers of certain AI systems',
                publisher: 'European Commission',
                publishedAt: '2026-07-20',
                url: 'https://digital-strategy.ec.europa.eu/en/news/commission-publishes-guidelines-transparency-obligations-providers-and-deployers-certain-ai-systems',
                perspective: 'Official implementation guidance for Article 50 transparency duties applying from 2 August 2026',
            },
            {
                title: 'AI Omnibus enters into force',
                publisher: 'European Commission',
                publishedAt: '2026-07-27',
                url: 'https://digital-strategy.ec.europa.eu/en/news/ai-omnibus-enters-force',
                perspective: 'Official summary of revised high-risk deadlines and governance changes',
            },
        ],
        waypoints: [
            {
                nodeId: 'Europe',
                title: 'A Staged Rulebook',
                narration: 'The AI Act uses different application dates: some rules applied in 2025, transparency duties apply from 2 August 2026, and high-risk-system deadlines now fall later.',
                focusQuestion: 'Why can saying a law is “in force” obscure which duties actually apply today?',
            },
            {
                nodeId: 'TechAIHub',
                title: 'Recognizing Synthetic Content',
                narration: 'Article 50 transparency duties cover specified AI interactions and machine-readable marking or visible labelling for defined categories of generated or manipulated content.',
                focusQuestion: 'When does a label improve informed choice, and when might it become background noise?',
            },
            {
                nodeId: 'Europe',
                title: 'Deadlines Recalibrated',
                narration: 'The Commission says the AI Omnibus moved the main high-risk-system deadline to December 2027 and the product-embedded deadline to August 2028.',
                focusQuestion: 'How should governments balance implementation readiness against the cost of delaying safeguards?',
            },
            {
                nodeId: 'TechAIHub',
                title: 'From Text to Enforcement',
                narration: 'Guidelines and voluntary codes can support compliance, but enforcement practice, technical standards, and user understanding will shape real-world effects.',
                focusQuestion: 'Which evidence would show that transparency rules change provider behavior or public understanding?',
            },
        ],
    },
];

/**
 * Adapt a canonical case study to the legacy forecast record shape while
 * retaining evidence metadata for source-aware consumers.
 */
export function toForecastRecord(caseStudy) {
    if (!caseStudy || typeof caseStudy !== 'object') {
        throw new TypeError('toForecastRecord requires a case-study object');
    }

    const primarySource = caseStudy.sources?.[0];
    const sourceLabel = (caseStudy.sources || [])
        .map(source => `${source.publisher}: ${source.title}${source.publishedAt ? ` (${source.publishedAt})` : ''}`)
        .join('; ');

    return {
        'Topic/Sector': caseStudy.issueDimensions.join(' / '),
        'Entity/Subject': caseStudy.title,
        'Key Player/Organization': caseStudy.actors.join(', '),
        Timeline: `Current as of ${caseStudy.updatedAt}`,
        'Expected Impact/Value': `${caseStudy.statusSummary} ${caseStudy.whyItMatters}`,
        Source: sourceLabel,
        url: primarySource?.url || '',
        Latitude: String(caseStudy.coordinates.latitude),
        Longitude: String(caseStudy.coordinates.longitude),
        Broad_Category: caseStudy.broadCategory,
        caseStudyId: caseStudy.id,
        statusSummary: caseStudy.statusSummary,
        whyItMatters: caseStudy.whyItMatters,
        issueDimensions: [...caseStudy.issueDimensions],
        regionTags: [...caseStudy.regionTags],
        nexusActorIds: [...caseStudy.nexusNodeIds],
        updatedAt: caseStudy.updatedAt,
        confidence: caseStudy.confidence,
        uncertainty: caseStudy.uncertainty,
        sources: caseStudy.sources.map(source => ({ ...source })),
        waypoints: caseStudy.waypoints.map(waypoint => ({ ...waypoint })),
        isCaseStudy: true,
        isEditorial: true,
    };
}

export default CASE_STUDIES_2026;
