/**
 * Africa and MENA case studies prepared for the 2026 Guided Briefings feed.
 *
 * Current-status claims remain attributed to the linked sources. The records
 * deliberately separate local, institutional, and independent perspectives so
 * that a briefing does not collapse a contested issue into one official view.
 */
export const AFRICA_MENA_CASE_STUDIES_2026 = [
    {
        id: 'eastern-drc-peace-civilian-protection',
        title: 'Eastern DRC: Peace Agreements, Armed Authority, and Civilian Protection',
        subtitle: 'Testing whether parallel diplomacy can change conditions in the Great Lakes',
        regionTags: ['Africa', 'Great Lakes', 'Central Africa'],
        issueDimensions: ['Peace implementation', 'Cross-border security', 'Civilian protection', 'Forced displacement', 'Humanitarian access'],
        actors: ['Government of the Democratic Republic of the Congo', 'AFC/M23', 'Government of Rwanda', 'Eastern Congolese communities', 'African and United Nations mediators'],
        nexusNodeIds: ['Africa', 'MilitantPMC', 'UN_OPEC'],
        statusSummary: 'The Congolese presidency describes the June 2025 DRC–Rwanda agreement as a framework for peace and regional economic integration. The UN Security Council sanctions committee added the Alliance Fleuve Congo to its sanctions list in July 2026, while Institute for Security Studies analysis argues that overlapping mediation tracks still face coordination, deterrence, and implementation gaps.',
        whyItMatters: 'The case tests whether agreements among states and armed actors can improve civilian protection when authority, security guarantees, and accountability remain fragmented across borders.',
        updatedAt: '2026-08-09',
        confidence: 'medium',
        uncertainty: 'Territorial control, armed-group alliances, displacement, and humanitarian access can change rapidly. Government, armed-group, and international descriptions of responsibility remain contested and should always be attributed.',
        coordinates: { latitude: -1.6585, longitude: 29.2205 },
        broadCategory: 'Geopolitics & Conflict',
        coverageRegion: 'Sub-Saharan Africa',
        featured: true,
        sensitivity: 'high',
        editorialCaution: 'Attribute recognition, sovereignty, and territorial-integrity claims to their proponents; represent contested eastern-area positions as internally diverse; and do not infer unconfirmed security arrangements or future recognitions.',
        reviewCadenceDays: 14,
        reviewBy: '2026-08-23',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Kinshasa', latitude: -4.4419, longitude: 15.2663 },
                { label: 'Goma', latitude: -1.6585, longitude: 29.2205 },
                { label: 'Bukavu', latitude: -2.5036, longitude: 28.8608 },
                { label: 'Kigali', latitude: -1.9441, longitude: 30.0619 },
            ],
        },
        sources: [
            {
                title: 'The DRC and Rwanda Sign a Peace Agreement in Washington',
                publisher: 'Presidency of the Democratic Republic of the Congo',
                publishedAt: '2025-06-27',
                url: 'https://www.presidence.cd/actualite-detail/actualite/exclusif_la_rdc_et_le_rwanda_ont_signe_un_accord_de_paix_ce_vendredi_aux_etats_unis_damerique',
                perspectiveType: 'local',
                perspective: 'Official Congolese account of the agreement and the government\'s peace and integration objectives',
                supports: 'Supports the attributed description of how the Congolese government presents the DRC–Rwanda agreement.',
            },
            {
                title: 'Alliance Fleuve Congo (AFC)',
                publisher: 'United Nations Security Council',
                publishedAt: '2026-07-14',
                url: 'https://main.un.org/securitycouncil/en/content/alliance-fleuve-congo-afc',
                perspectiveType: 'institutional',
                perspective: 'United Nations sanctions record identifying the organization and the basis for its listing',
                supports: 'Supports the current institutional status of AFC and the need to distinguish diplomatic agreements from sanctions enforcement.',
            },
            {
                title: 'Diplomacy without deterrence won\'t bring peace in eastern DRC',
                publisher: 'Institute for Security Studies',
                publishedAt: '2025-08-15',
                url: 'https://issafrica.org/iss-today/diplomacy-without-deterrence-won-t-bring-peace-in-eastern-drc',
                perspectiveType: 'independent',
                perspective: 'Independent African policy analysis of mediation, enforcement, and regional security incentives',
                supports: 'Supports the analytical caution that multiple negotiation tracks do not by themselves guarantee implementation or civilian protection.',
            },
        ],
        waypoints: [
            {
                nodeId: 'Africa',
                title: 'Civilian Security as the Test',
                perspectiveLabel: 'Eastern Congolese communities',
                perspectiveType: 'local',
                narration: 'For people living around Goma, Bukavu, and rural conflict zones, an agreement matters only if it changes safety, mobility, access to services, and the ability to return home.',
                focusQuestion: 'Which civilian indicators would show that diplomacy is changing daily life rather than only state-to-state relations?',
            },
            {
                nodeId: 'Africa',
                title: 'The State Peace Framework',
                perspectiveLabel: 'Congolese government position',
                perspectiveType: 'local',
                narration: 'The Congolese presidency presents the DRC–Rwanda agreement as a route toward peace, sovereignty, and regional economic integration.',
                focusQuestion: 'What institutions and verification mechanisms are needed to turn a bilateral framework into security on the ground?',
            },
            {
                nodeId: 'MilitantPMC',
                title: 'Armed Authority and Leverage',
                perspectiveLabel: 'AFC/M23 and armed networks',
                perspectiveType: 'independent',
                narration: 'Armed organizations retain territorial and political leverage even while state and international actors pursue parallel negotiation and sanctions tracks.',
                focusQuestion: 'How should a peace process engage an armed actor without normalizing coercive territorial control?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Coordination and Enforcement',
                perspectiveLabel: 'Regional and multilateral mediators',
                perspectiveType: 'institutional',
                narration: 'Sanctions, monitoring, African mediation, and international diplomacy create several accountability channels, but their mandates and incentives do not automatically align.',
                focusQuestion: 'Who should verify compliance, coordinate pressure, and respond when commitments are breached?',
            },
        ],
    },
    {
        id: 'sahel-after-ecowas-regional-order',
        title: 'The Sahel After ECOWAS: Competing Regional Orders',
        subtitle: 'Integration, sovereignty, and security after the AES withdrawal',
        regionTags: ['Africa', 'Sahel', 'West Africa'],
        issueDimensions: ['Regional integration', 'Military rule', 'Counterterrorism', 'Mobility and trade', 'Civilian protection'],
        actors: ['Alliance of Sahel States', 'ECOWAS', 'Border communities and traders', 'Coastal West African states', 'African Union and United Nations offices'],
        nexusNodeIds: ['Africa', 'UN_OPEC', 'Jihadist'],
        statusSummary: 'ECOWAS stated that Burkina Faso, Mali, and Niger formally withdrew in January 2025 while temporary arrangements preserved movement and trade during negotiations. A July 2026 UNOWAS briefing called for dialogue amid continuing insecurity, and Institute for Security Studies analysis warns that fragmented regional security initiatives can duplicate effort and weaken accountability.',
        whyItMatters: 'The split forces governments and citizens to renegotiate how security cooperation, cross-border movement, trade, and political legitimacy work across a region where threats and livelihoods do not stop at institutional borders.',
        updatedAt: '2026-08-09',
        confidence: 'medium',
        uncertainty: 'The legal and operational relationship between ECOWAS and the Alliance of Sahel States is still evolving. Security reporting is uneven, and official claims about counterterrorism effectiveness require independent corroboration.',
        coordinates: { latitude: 13.5116, longitude: 2.1254 },
        broadCategory: 'Geopolitics & Conflict',
        coverageRegion: 'Sub-Saharan Africa',
        featured: false,
        sensitivity: 'high',
        reviewCadenceDays: 14,
        reviewBy: '2026-08-23',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Bamako', latitude: 12.6392, longitude: -8.0029 },
                { label: 'Ouagadougou', latitude: 12.3714, longitude: -1.5197 },
                { label: 'Niamey', latitude: 13.5116, longitude: 2.1254 },
                { label: 'Abuja', latitude: 9.0765, longitude: 7.3986 },
            ],
        },
        sources: [
            {
                title: 'Press Statement on the Withdrawal of Burkina Faso, Mali and Niger from ECOWAS',
                publisher: 'Economic Community of West African States',
                publishedAt: '2025-01-30',
                url: 'https://www.ecowas.int/press-statement-2/',
                perspectiveType: 'local',
                perspective: 'West African regional organization account of the withdrawal and temporary transition arrangements',
                supports: 'Supports the effective withdrawal date and ECOWAS\'s stated approach to movement, residence, and trade during negotiations.',
            },
            {
                title: 'Before the Security Council, Special Representative Leonardo Santos Simão Calls for Renewed Regional Cooperation',
                publisher: 'United Nations Office for West Africa and the Sahel',
                publishedAt: '2026-07-14',
                url: 'https://unowas.unmissions.org/en/news/before-the-security-council-special-representative-leonardo-santos-simao-calls-for',
                perspectiveType: 'institutional',
                perspective: 'United Nations regional assessment of political dialogue, security pressure, and cross-border cooperation',
                supports: 'Supports the claim that insecurity and political fragmentation continue to require cooperation beyond current blocs.',
            },
            {
                title: 'How ECOWAS can make its new counter-terrorism force effective',
                publisher: 'Institute for Security Studies',
                publishedAt: '2026-03-25',
                url: 'https://issafrica.org/iss-today/how-ecowas-can-make-its-new-counter-terrorism-force-effective',
                perspectiveType: 'independent',
                perspective: 'Independent African analysis of force design, regional duplication, finance, and accountability',
                supports: 'Supports scrutiny of whether new security structures resolve or reproduce coordination problems.',
            },
        ],
        waypoints: [
            {
                nodeId: 'Africa',
                title: 'Sovereignty and Regional Reordering',
                perspectiveLabel: 'Alliance of Sahel States',
                perspectiveType: 'local',
                narration: 'The AES governments frame institutional separation as a sovereignty project and are building their own mechanisms for diplomacy, security, and economic coordination.',
                focusQuestion: 'What would make a new regional institution legitimate to both governments and the populations it affects?',
            },
            {
                nodeId: 'Africa',
                title: 'Borders as Lived Infrastructure',
                perspectiveLabel: 'Border communities and traders',
                perspectiveType: 'local',
                narration: 'Temporary protections for movement and trade acknowledge that households, markets, and transport corridors remain integrated despite the political split.',
                focusQuestion: 'Which cross-border rights and services must be protected regardless of institutional membership?',
            },
            {
                nodeId: 'Jihadist',
                title: 'A Threat That Crosses Blocs',
                perspectiveLabel: 'Regional security analysts',
                perspectiveType: 'independent',
                narration: 'Armed networks exploit weak governance and border spaces, making duplicated forces, incompatible intelligence systems, and unclear accountability consequential.',
                focusQuestion: 'Can competing security coalitions cooperate without erasing civilian oversight?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Negotiated Coexistence',
                perspectiveLabel: 'ECOWAS, African Union, and United Nations',
                perspectiveType: 'institutional',
                narration: 'Regional and multilateral institutions continue to advocate dialogue because humanitarian, economic, and security systems remain interdependent.',
                focusQuestion: 'What minimum framework could preserve cooperation while respecting the political split?',
            },
        ],
    },
    {
        id: 'somaliland-recognition-red-sea-order',
        title: 'Somaliland Recognition and the Red Sea Order',
        subtitle: 'Self-determination, territorial integrity, and a new diplomatic precedent',
        regionTags: ['Africa', 'Horn of Africa', 'Red Sea'],
        issueDimensions: ['Recognition diplomacy', 'Self-determination', 'Territorial integrity', 'Maritime security', 'Regional order'],
        actors: ['Somaliland authorities', 'Federal Government of Somalia', 'Israel', 'African Union, IGAD, and United Nations', 'Communities in contested eastern areas'],
        nexusNodeIds: ['Africa', 'MiddleEast', 'UN_OPEC'],
        statusSummary: 'A Somaliland foreign-ministry official welcomed Israel\'s 26 December 2025 recognition as a statehood milestone and basis for broader partnership. A 29 December United Nations political-affairs briefing recorded Somaliland\'s statement that the recognition established full diplomatic relations and Somalia\'s rejection, while Associated Press reporting documented the subsequent high-level visit and the wider dispute over sovereignty, precedent, and Red Sea strategy.',
        whyItMatters: 'The case links a long-running claim to statehood with African norms on inherited borders, Somalia\'s territorial-integrity claim, Middle Eastern diplomacy, and competition around Red Sea ports and security routes.',
        updatedAt: '2026-08-10',
        confidence: 'medium',
        uncertainty: 'Recognition policy can change, terminology is politically contested, and views within Somaliland and the disputed eastern territories are not uniform. Claims about security arrangements or future recognitions require direct confirmation.',
        coordinates: { latitude: 9.5624, longitude: 44.0770 },
        broadCategory: 'Geopolitics & Conflict',
        coverageRegion: 'Horn of Africa and Red Sea',
        featured: true,
        sensitivity: 'high',
        reviewCadenceDays: 14,
        reviewBy: '2026-08-24',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Hargeisa', latitude: 9.5624, longitude: 44.0770, role: 'Somaliland authorities and statehood claim' },
                { label: 'Berbera', latitude: 10.4396, longitude: 45.0143, role: 'Red Sea port and maritime-strategy reference point' },
                { label: 'Las Anod / Laascaanood', latitude: 8.4774, longitude: 47.3597, role: 'Contested eastern-area and SSC-Khaatumo perspective reference point' },
                { label: 'Mogadishu', latitude: 2.0469, longitude: 45.3182, role: 'Federal Government of Somalia territorial-integrity position' },
                { label: 'Jerusalem', latitude: 31.7683, longitude: 35.2137, role: 'Israeli recognition and bilateral-diplomacy reference point' },
            ],
        },
        sources: [
            {
                title: 'A Diplomatic Breakthrough: Somaliland’s Foreign DG hails Israel’s Recognition of Sovereignty',
                publisher: 'The Horn Tribune',
                publishedAt: '2025-12-29',
                url: 'https://horntribune.com/2025/12/29/a-diplomatic-breakthrough-somalilands-foreign-ministry-director-general-marks-israels-recognition-of-sovereignty/',
                alternateUrls: [
                    {
                        label: 'The Horn Tribune print edition — 4 January 2026, front-page lead and page 5 continuation',
                        url: 'https://horntribune.com/wp-content/uploads/2026/01/THT-04-January-2026front.pdf',
                    },
                ],
                perspectiveType: 'local',
                perspective: 'Somaliland-based reporting of an interview with the foreign ministry director general, presenting the authorities\' statehood case and intended areas of partnership',
                supports: 'Supports the attributed Somaliland foreign-ministry view that Israel\'s 26 December 2025 recognition was welcomed as a statehood milestone and a basis for expanded bilateral cooperation in diplomacy, trade, tourism, and agriculture.',
            },
            {
                title: 'Assistant Secretary-General Khiari Briefs the Security Council on Somalia',
                publisher: 'United Nations Department of Political and Peacebuilding Affairs',
                publishedAt: '2025-12-29',
                url: 'https://dppa.dfs.un.org/en/mtg-sc-10084-asg-khiari-29-dec-2025',
                perspectiveType: 'institutional',
                perspective: 'United Nations record of the recognition, Somalia\'s response, and regional institutional concerns',
                supports: 'Supports the description of the competing recognition and territorial-integrity positions in a multilateral forum.',
            },
            {
                title: 'Israel\'s foreign minister visits Somaliland after recognizing the breakaway region',
                publisher: 'Associated Press',
                publishedAt: '2026-01-06',
                url: 'https://apnews.com/article/2447736e7355da4ac1ed182771f2e85e',
                perspectiveType: 'independent',
                perspective: 'Independent reporting on the diplomatic visit and the contested regional response',
                supports: 'Supports the follow-on diplomatic activity and independently documents disagreement over the recognition decision.',
            },
        ],
        supplementalSources: [
            {
                title: 'Why SSC-Khaatumo opposes Somaliland’s bid for recognition',
                publisher: 'The EastAfrican',
                publishedAt: '2025-06-04',
                url: 'https://www.theeastafrican.co.ke/tea/news/east-africa/why-ssc-khaatumo-opposes-somaliland-s-bid-for-recognition-5086894',
                perspective: 'Regional reporting that attributes opposition to Somaliland\'s recognition and territorial claims to SSC-Khaatumo officials',
                supports: 'Supports the attributed claim that political and territorial preferences in Sool, Sanaag, and Cayn are contested.',
            },
        ],
        waypoints: [
            {
                nodeId: 'Africa',
                title: 'The Statehood Claim',
                perspectiveLabel: 'Somaliland authorities and supporters',
                perspectiveType: 'local',
                narration: 'Somaliland presents its institutions, security record, and separate political history as the basis for international recognition.',
                focusQuestion: 'Which legal and political criteria should determine whether a long-standing de facto state receives recognition?',
            },
            {
                nodeId: 'Africa',
                title: 'Territorial Integrity and Internal Plurality',
                perspectiveLabel: 'Somalia and contested-area communities',
                perspectiveType: 'local',
                narration: 'Somalia rejects recognition as a violation of territorial integrity, while communities in disputed eastern areas complicate any claim that one local view is universal.',
                focusQuestion: 'How should recognition policy account for both territorial integrity and non-uniform local preferences?',
            },
            {
                nodeId: 'MiddleEast',
                title: 'Recognition as Strategy',
                perspectiveLabel: 'Israeli diplomatic calculus',
                perspectiveType: 'institutional',
                narration: 'Recognition adds a Middle Eastern diplomatic actor to a Horn of Africa question already linked to ports, maritime routes, and regional security.',
                focusQuestion: 'When does bilateral recognition alter a regional order rather than merely signal a political preference?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'The Precedent Question',
                perspectiveLabel: 'African and multilateral institutions',
                perspectiveType: 'synthesis',
                narration: 'The African Union, IGAD, and United Nations must weigh self-determination claims against inherited-border norms and escalation risks.',
                focusQuestion: 'What process could evaluate recognition claims without turning every disputed border into a security crisis?',
            },
        ],
    },
    {
        id: 'zambia-electricity-reset-climate-access',
        title: 'Zambia\'s Electricity Reset: Copper, Climate, and Access',
        subtitle: 'Who benefits as a hydropower-dependent system diversifies',
        regionTags: ['Africa', 'Southern Africa', 'Zambezi Basin'],
        issueDimensions: ['Energy security', 'Climate resilience', 'Critical minerals', 'Affordability and access', 'Regional power trade'],
        actors: ['Zambian Ministry of Energy and ZESCO', 'Households and small businesses', 'Copper mining companies', 'Renewable-energy developers', 'Zambezi River Authority and regional power pool'],
        nexusNodeIds: ['Africa', 'TechAIHub', 'UN_OPEC'],
        statusSummary: 'Zambia\'s Ministry of Energy reported in July 2026 that the sustained load-shedding period had ended and highlighted new solar capacity and access initiatives. The Zambezi River Authority continues to publish changing Kariba storage and lake-level conditions, while World Bank analysis argues that drought exposed the costs of hydropower dependence and unequal electricity access.',
        whyItMatters: 'Reliable electricity links household welfare and public services to copper production, digital infrastructure, climate adaptation, water governance, and regional power trade. Diversification choices will distribute benefits and costs unevenly.',
        updatedAt: '2026-08-09',
        confidence: 'medium',
        uncertainty: 'Generation availability, reservoir inflows, demand, tariffs, and load management change with weather and operations. Government announcements should be checked against utility performance and household experience.',
        coordinates: { latitude: -15.3875, longitude: 28.3228 },
        broadCategory: 'Environment & Energy',
        coverageRegion: 'Southern Africa',
        featured: false,
        sensitivity: 'standard',
        reviewCadenceDays: 30,
        reviewBy: '2026-09-08',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Lusaka', latitude: -15.3875, longitude: 28.3228 },
                { label: 'Kariba North Bank', latitude: -16.5217, longitude: 28.7610 },
                { label: 'Kitwe and the Copperbelt', latitude: -12.8024, longitude: 28.2132 },
                { label: 'Harare and the regional power pool', latitude: -17.8252, longitude: 31.0335 },
            ],
        },
        sources: [
            {
                title: 'Key Highlights in Zambia\'s Energy Sector',
                publisher: 'Ministry of Energy, Republic of Zambia',
                publishedAt: '2026-07-29',
                url: 'https://www.moe.gov.zm/?p=6323',
                perspectiveType: 'local',
                perspective: 'Official Zambian account of power availability, solar deployment, and electricity-access initiatives',
                supports: 'Supports the attributed government description of the 2026 electricity reset and diversification measures.',
            },
            {
                title: 'Lake Kariba Levels',
                publisher: 'Zambezi River Authority',
                publishedAt: null,
                sourceType: 'living-reference',
                dataThrough: '2026-08-04',
                reviewedAt: '2026-08-09',
                url: 'https://www.zambezira.org/hydrology/lake-levels',
                perspectiveType: 'institutional',
                perspective: 'Bilateral river-basin authority operational data on changing Kariba water levels and storage',
                supports: 'Supports treating hydrological conditions as a dynamic constraint that requires recurring review.',
            },
            {
                title: 'Powering Zambia\'s Transformation: From Electricity Crisis to Catalyst for Growth and Jobs',
                publisher: 'World Bank',
                publishedAt: '2026-05-08',
                url: 'https://www.worldbank.org/en/country/zambia/publication/powering-zambia-s-transformation-from-electricity-crisis-to-catalyst-for-growth-and-jobs',
                perspectiveType: 'independent',
                perspective: 'External development analysis of drought exposure, investment needs, access, and distributional impacts',
                supports: 'Supports analysis of structural hydropower dependence and the need to measure who gains from sector reform.',
            },
        ],
        waypoints: [
            {
                nodeId: 'Africa',
                title: 'Reliability in Daily Life',
                perspectiveLabel: 'Households and small businesses',
                perspectiveType: 'local',
                narration: 'The practical test of recovery is whether homes, clinics, schools, and small firms receive reliable and affordable power, not only whether national generation rises.',
                focusQuestion: 'Which reliability and affordability indicators should determine whether the reset is working?',
            },
            {
                nodeId: 'Africa',
                title: 'Diversifying the Power System',
                perspectiveLabel: 'Zambian energy institutions',
                perspectiveType: 'local',
                narration: 'The government is pairing restored supply with solar projects and access initiatives intended to reduce dependence on a single weather-sensitive generation source.',
                focusQuestion: 'How quickly can diversification improve resilience without creating unaffordable costs?',
            },
            {
                nodeId: 'TechAIHub',
                title: 'Copper and New Electricity Demand',
                perspectiveLabel: 'Mining and clean-energy supply chains',
                perspectiveType: 'independent',
                narration: 'Copper production can finance development and supply global electrification, but large industrial demand can also compete with underserved users for scarce power.',
                focusQuestion: 'How should Zambia balance export-led industrial demand with universal access?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Shared Water, Shared Grid',
                perspectiveLabel: 'River and regional power institutions',
                perspectiveType: 'institutional',
                narration: 'Kariba is jointly governed and Zambia trades within a regional electricity system, making climate resilience a cross-border coordination problem.',
                focusQuestion: 'Which regional rules can spread risk while preserving fair access to shared water and electricity?',
            },
        ],
    },
    {
        id: 'western-sahara-autonomy-self-determination',
        title: 'Western Sahara: Self-Determination, Autonomy, and Representation',
        subtitle: 'A territorial dispute reshaped by diplomacy and competing interpretations of consent',
        regionTags: ['Africa', 'North Africa', 'Maghreb'],
        issueDimensions: ['Self-determination', 'Autonomy', 'Territorial status', 'Political participation', 'Human rights'],
        actors: ['Sahrawi residents and refugees', 'Morocco', 'Polisario Front and Sahrawi Arab Democratic Republic', 'Algeria', 'United Nations and MINURSO'],
        nexusNodeIds: ['Africa', 'UN_OPEC', 'Europe'],
        statusSummary: 'UN Security Council Resolution 2797 extended MINURSO through October 2026 and made Morocco\'s autonomy proposal a basis for negotiations while retaining language on self-determination. Morocco\'s foreign ministry presents autonomy under Moroccan sovereignty as the most feasible solution; Human Rights Watch argues that the framework risks narrowing meaningful self-determination and calls for genuine Sahrawi participation.',
        whyItMatters: 'The dispute tests how international institutions reconcile territorial claims, self-determination, human rights, refugee representation, and the different meanings parties attach to an acceptable political settlement.',
        updatedAt: '2026-08-09',
        confidence: 'medium',
        uncertainty: 'Sovereignty and legal terminology are contested, access to the territory and refugee camps is asymmetric, and Sahrawi views are not uniform. No source should be treated as speaking for every affected person.',
        coordinates: { latitude: 27.1536, longitude: -13.2033 },
        broadCategory: 'Geopolitics & Conflict',
        coverageRegion: 'North Africa',
        featured: false,
        sensitivity: 'high',
        reviewCadenceDays: 30,
        reviewBy: '2026-09-08',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Laayoune / El Aaiún', latitude: 27.1536, longitude: -13.2033 },
                { label: 'Tindouf refugee camps', latitude: 27.6742, longitude: -8.1478 },
                { label: 'Rabat', latitude: 34.0209, longitude: -6.8416 },
                { label: 'Algiers', latitude: 36.7538, longitude: 3.0588 },
            ],
        },
        sources: [
            {
                title: 'Moroccan Sahara: Spain Welcomes the Adoption of Resolution 2797',
                publisher: 'Ministry of Foreign Affairs, African Cooperation and Moroccan Expatriates',
                publishedAt: '2025-12-04',
                url: 'https://diplomatie.ma/en/moroccan-sahara-spain-welcomes-adoption-resolution-2797-which-emphasizes-genuine-autonomy-under-moroccan-sovereignty-most-feasible-solution',
                perspectiveType: 'local',
                perspective: 'Official Moroccan presentation of autonomy under Moroccan sovereignty and international support for that approach',
                supports: 'Supports the attributed Moroccan interpretation of Resolution 2797 and its preferred negotiating outcome.',
            },
            {
                title: 'Security Council Resolution 2797 (2025)',
                publisher: 'United Nations Digital Library',
                publishedAt: '2025-10-31',
                url: 'https://digitallibrary.un.org/record/4093666?ln=en',
                perspectiveType: 'institutional',
                perspective: 'Official resolution record, vote, and extension of the MINURSO mandate through October 2026',
                supports: 'Supports the institutional status of the UN mission and the formal framework under which negotiations continue.',
            },
            {
                title: 'UN: Western Sahara Peoples\' Self-Determination at Risk',
                publisher: 'Human Rights Watch',
                publishedAt: '2026-03-25',
                url: 'https://www.hrw.org/news/2026/03/25/un-western-sahara-peoples-self-determination-at-risk',
                perspectiveType: 'independent',
                perspective: 'Independent rights-based critique of the negotiating framework and the adequacy of Sahrawi participation',
                supports: 'Supports scrutiny of whether the process preserves meaningful self-determination and human-rights safeguards.',
            },
        ],
        waypoints: [
            {
                nodeId: 'Africa',
                title: 'Lives Behind Competing Claims',
                perspectiveLabel: 'Sahrawi residents and refugees',
                perspectiveType: 'local',
                narration: 'People living in the territory and in refugee camps experience different institutions, restrictions, and futures, and should not be represented as a single undifferentiated voice.',
                focusQuestion: 'How can a political process establish whose consent is required and how that consent will be expressed?',
            },
            {
                nodeId: 'Africa',
                title: 'Autonomy Under Sovereignty',
                perspectiveLabel: 'Moroccan government position',
                perspectiveType: 'local',
                narration: 'Morocco presents negotiated autonomy under its sovereignty as the most feasible and durable outcome.',
                focusQuestion: 'What powers, guarantees, and accountability mechanisms would make an autonomy proposal meaningful in practice?',
            },
            {
                nodeId: 'Africa',
                title: 'Self-Determination With an Independence Option',
                perspectiveLabel: 'Polisario and independence supporters',
                perspectiveType: 'independent',
                narration: 'Polisario and independence supporters reject a process that excludes independence and argue that the political status must reflect a free act of self-determination.',
                focusQuestion: 'Can a negotiation be mutually acceptable if one side believes a core status option has been removed in advance?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Mandate, Mediation, and Rights',
                perspectiveLabel: 'United Nations process',
                perspectiveType: 'institutional',
                narration: 'Resolution 2797 keeps MINURSO in place and supplies a negotiating framework, while disagreements persist over how it should protect self-determination and rights.',
                focusQuestion: 'How should mediators measure whether a settlement is both politically feasible and rights-consistent?',
            },
        ],
    },
    {
        id: 'libya-roadmap-elections-oil-assets',
        title: 'Libya\'s 2026 Roadmap: Elections, Oil Assets, and Competing Authority',
        subtitle: 'Can structured dialogue produce unified institutions and accountable public finance?',
        regionTags: ['Africa', 'North Africa', 'Mediterranean'],
        issueDimensions: ['Political transition', 'Elections', 'Institutional unification', 'Oil and sovereign assets', 'Public finance', 'Human mobility'],
        actors: ['Libyan voters and civil society', 'Rival political and security institutions', 'High National Elections Commission', 'UNSMIL and Security Council', 'Central Bank, National Oil Corporation, and Libyan Investment Authority'],
        nexusNodeIds: ['Africa', 'UN_OPEC', 'MilitantPMC', 'Europe'],
        statusSummary: 'Libyan reporting describes the UN-facilitated roadmap as focused on completing the electoral framework and resolving the High National Elections Commission board impasse. Security Council Resolution 2819 adjusted measures governing Libyan assets in April 2026, while Chatham House analysis argues that external power-sharing proposals risk reinforcing elite fragmentation rather than producing accountable national institutions.',
        whyItMatters: 'Libya links delayed elections to divided security authority, oil-revenue governance, sovereign assets, public services, and migration across the Mediterranean. A roadmap can succeed procedurally while leaving the political economy of division intact.',
        updatedAt: '2026-08-09',
        confidence: 'medium',
        uncertainty: 'Timelines, elite bargains, security alignments, and oil flows can shift quickly. Rival institutions issue incompatible claims, and national-level reporting can obscure important municipal and civil-society perspectives.',
        coordinates: { latitude: 32.8872, longitude: 13.1913 },
        broadCategory: 'Geopolitics & Conflict',
        coverageRegion: 'North Africa and Mediterranean',
        featured: false,
        sensitivity: 'high',
        reviewCadenceDays: 14,
        reviewBy: '2026-08-23',
        map: {
            mode: 'regional',
            locations: [
                { label: 'Tripoli', latitude: 32.8872, longitude: 13.1913 },
                { label: 'Benghazi', latitude: 32.1194, longitude: 20.0868 },
                { label: 'Sabha', latitude: 27.0377, longitude: 14.4283 },
                { label: 'Sirte', latitude: 31.2089, longitude: 16.5887 },
            ],
        },
        sources: [
            {
                title: 'UN-led talks in Libya seek ways to break electoral deadlock',
                publisher: 'The Libya Observer',
                publishedAt: '2026-08-02',
                url: 'https://libyaobserver.ly/news/un-led-talks-libya-seek-ways-break-electoral-deadlock',
                perspectiveType: 'local',
                perspective: 'Libyan news reporting on the structured dialogue, election obstacles, and domestic political response',
                supports: 'Supports the current description of the electoral-law and election-commission issues within the roadmap.',
            },
            {
                title: 'Security Council Resolution 2819 (2026)',
                publisher: 'United Nations Security Council',
                publishedAt: '2026-04-14',
                url: 'https://main.un.org/securitycouncil/en/content/sres28192026',
                perspectiveType: 'institutional',
                perspective: 'Official multilateral decision on Libya sanctions, sovereign assets, and illicit petroleum measures',
                supports: 'Supports the institutional status of asset-related measures and the link between political authority and resource governance.',
            },
            {
                title: 'Why US plans for power-sharing in Libya will not work',
                publisher: 'Chatham House',
                publishedAt: '2026-07-24',
                url: 'https://www.chathamhouse.org/2026/07/why-us-plans-power-sharing-libya-will-not-work',
                perspectiveType: 'independent',
                perspective: 'Independent analysis of elite bargaining, divided institutions, and risks in externally sponsored power-sharing',
                supports: 'Supports scrutiny of whether a negotiated elite arrangement would unify institutions or preserve fragmented authority.',
            },
        ],
        waypoints: [
            {
                nodeId: 'Africa',
                title: 'A Public Demand for a Political Endpoint',
                perspectiveLabel: 'Libyan voters and civil society',
                perspectiveType: 'local',
                narration: 'Many Libyans seek elections and functioning services, but their priorities can be displaced by bargaining among institutions that benefit from an extended transition.',
                focusQuestion: 'How can the roadmap give citizens leverage over the actors negotiating its terms?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'From Rules to a Credible Vote',
                perspectiveLabel: 'HNEC and UN-facilitated roadmap',
                perspectiveType: 'institutional',
                narration: 'The immediate process centers on electoral rules, a functioning election commission, and a structured dialogue intended to address barriers beyond election mechanics.',
                focusQuestion: 'Which sequencing choices are necessary for a vote to be accepted rather than simply held?',
            },
            {
                nodeId: 'MilitantPMC',
                title: 'Security Authority Outside a Unified State',
                perspectiveLabel: 'Rival political and armed institutions',
                perspectiveType: 'local',
                narration: 'Competing security structures and territorial power centers can veto, delay, or selectively enforce national political agreements.',
                focusQuestion: 'What security guarantees would allow institutions and candidates to participate without coercive advantage?',
            },
            {
                nodeId: 'Africa',
                title: 'Oil Wealth and Public Accountability',
                perspectiveLabel: 'Independent political-economy analysis',
                perspectiveType: 'independent',
                narration: 'Oil revenue and sovereign assets can finance recovery, but divided spending authority and weak oversight also sustain political fragmentation.',
                focusQuestion: 'Which transparent fiscal rules would make institutional unification materially valuable to the public?',
            },
        ],
    },
    {
        id: 'red-sea-yemen-humanitarian-economy',
        title: 'Red Sea Security Through Yemen\'s Humanitarian Economy',
        subtitle: 'Shipping attacks, import dependence, and the costs borne by civilians',
        regionTags: ['Middle East', 'Red Sea', 'Horn of Africa'],
        issueDimensions: ['Maritime security', 'Seafarer safety', 'Trade finance', 'Food and medicine imports', 'Humanitarian access', 'Regional escalation'],
        actors: ['Yemeni civilians and importers', 'Ansar Allah/Houthi authorities', 'Internationally recognized Yemeni government', 'International Maritime Organization and shipping operators', 'Red Sea and Horn of Africa coastal states'],
        nexusNodeIds: ['MiddleEast', 'Hezbollah', 'UN_OPEC', 'Africa'],
        statusSummary: 'The Sana\'a Center describes a fragmented Yemeni trade-finance system that makes essential imports more costly and uncertain. The International Maritime Organization condemned renewed Red Sea attacks in July 2026 and highlighted risks to seafarers, supply chains, and the environment; Chatham House analysis warns that overlapping military and humanitarian activity increases escalation and miscalculation risks.',
        whyItMatters: 'Treating the Red Sea only as a global shipping lane hides how maritime coercion, port access, banking fragmentation, and import costs shape food, fuel, medicine, and livelihoods for people inside Yemen and around the corridor.',
        updatedAt: '2026-08-09',
        confidence: 'medium',
        uncertainty: 'Attack attribution, damage, shipping behavior, insurance costs, port access, and military deployments change rapidly. Economic effects vary across Yemen\'s divided monetary and political zones and require local corroboration.',
        coordinates: { latitude: 14.7979, longitude: 42.9545 },
        broadCategory: 'Geopolitics & Conflict',
        coverageRegion: 'Middle East and Red Sea',
        featured: true,
        sensitivity: 'high',
        reviewCadenceDays: 7,
        reviewBy: '2026-08-16',
        map: {
            mode: 'route',
            locations: [
                { label: 'Sana\'a', latitude: 15.3694, longitude: 44.1910 },
                { label: 'Hudaydah', latitude: 14.7979, longitude: 42.9545 },
                { label: 'Bab el-Mandeb', latitude: 12.5833, longitude: 43.3333 },
                { label: 'Aden', latitude: 12.7855, longitude: 45.0187 },
            ],
        },
        sources: [
            {
                title: 'Supporting Trade Finance in Yemen Amid Uncertainty',
                publisher: 'Sana\'a Center for Strategic Studies',
                publishedAt: '2026-02-17',
                url: 'https://sanaacenter.org/publications/policy-research/26389',
                perspectiveType: 'local',
                perspective: 'Yemeni-led economic research on divided banking systems, import finance, and household exposure',
                supports: 'Supports the claim that institutional fragmentation raises the cost and uncertainty of financing essential imports.',
            },
            {
                title: 'Statement on recent attacks in the Red Sea',
                publisher: 'International Maritime Organization',
                publishedAt: '2026-07-23',
                url: 'https://www.imo.org/en/mediacentre/pressbriefings/pages/statement-on-recent-attacks-in-the-red-sea.aspx',
                perspectiveType: 'institutional',
                perspective: 'International maritime-safety assessment centered on seafarers, navigation, supply chains, and environmental risk',
                supports: 'Supports the current institutional account of renewed attacks and their maritime and human consequences.',
            },
            {
                title: 'The Houthi Red Sea blockade: Will collective maritime security be defended, or break down?',
                publisher: 'Chatham House',
                publishedAt: '2026-07-24',
                url: 'https://www.chathamhouse.org/2026/07/houthi-red-sea-blockade-will-collective-maritime-security-be-defended-or-break-down',
                perspectiveType: 'independent',
                perspective: 'Independent analysis of escalation, overlapping naval operations, negotiations, and humanitarian movement',
                supports: 'Supports assessment of miscalculation risks created by competing security and humanitarian operations in the corridor.',
            },
        ],
        waypoints: [
            {
                nodeId: 'MiddleEast',
                title: 'The Import Economy',
                perspectiveLabel: 'Yemeni households, traders, and importers',
                perspectiveType: 'local',
                narration: 'Divided banks, currencies, and authorities make trade finance costly and unstable, transmitting maritime disruption into food, fuel, medicine, and livelihoods.',
                focusQuestion: 'Which policy changes would reduce civilian import costs without financing coercive actors?',
            },
            {
                nodeId: 'Hezbollah',
                title: 'Maritime Coercion as Armed Leverage',
                perspectiveLabel: 'Ansar Allah/Houthi strategy',
                perspectiveType: 'local',
                narration: 'Ansar Allah uses threats and attacks on shipping as regional leverage, linking the Yemen conflict to wider political and military contests.',
                focusQuestion: 'How should analysts distinguish the group\'s stated political aims from the effects of its actions on civilians and seafarers?',
            },
            {
                nodeId: 'MiddleEast',
                title: 'Ports, Government, and Divided Regulation',
                perspectiveLabel: 'Internationally recognized government and port institutions',
                perspectiveType: 'institutional',
                narration: 'Competing authorities govern ports, currency, and imports differently, so a single national indicator can conceal sharply different local economic conditions.',
                focusQuestion: 'What minimum coordination is required to keep essential trade moving across divided jurisdictions?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Safety Without Escalation',
                perspectiveLabel: 'Maritime and humanitarian institutions',
                perspectiveType: 'independent',
                narration: 'Seafarer safety, freedom of navigation, humanitarian access, and environmental protection overlap with military operations and diplomatic negotiations.',
                focusQuestion: 'Which collective-security measures can protect shipping while reducing risks to humanitarian access and regional escalation?',
            },
        ],
    },
];
