/**
 * Multi-perspective 2026 case studies covering the Americas, Europe, and
 * global governance. Current-status claims are attributed to the readings in
 * each record; analytical prompts are questions rather than predictions.
 */
export const AMERICAS_GLOBAL_CASE_STUDIES_2026 = [
    {
        id: 'haiti-security-legitimacy-haitian-ownership',
        title: 'Haiti: Security, Legitimacy, and Haitian Ownership',
        subtitle: 'Can international security support reinforce rather than displace Haitian institutions?',
        coverageRegion: 'Caribbean & Americas',
        featured: true,
        regionTags: ['Caribbean', 'Haiti', 'Americas'],
        issueDimensions: ['Public security', 'Political legitimacy', 'Civilian protection', 'International support'],
        actors: ['Haitian National Police', 'Haitian civil society', 'Haitian political authorities', 'Armed criminal groups', 'United Nations Support Office in Haiti'],
        nexusNodeIds: ['LatinAmerica', 'Cartels', 'UN_OPEC'],
        statusSummary: 'On 1 April 2026, the UN Secretary-General\'s spokesperson said the UN Support Office in Haiti was prepared to provide logistical and operational support to the Gang Suppression Force. A June 2026 RNDDH assessment, based on visits to 50 police posts, reported persistent personnel, equipment, infrastructure, and safety constraints within the Haitian National Police. Human Rights Watch separately describes a wider crisis of criminal-group violence, weak accountability, displacement, and contested transitional legitimacy.',
        whyItMatters: 'Haiti tests whether outside security assistance can protect civilians while strengthening accountable Haitian institutions, public trust, and a Haitian-owned political process.',
        updatedAt: '2026-06-12',
        confidence: 'high',
        uncertainty: 'Territorial control, police readiness, security-force deployment, and the electoral timetable can change rapidly. Operational and political claims require fresh Haitian and international verification before publication.',
        sensitivity: 'Do not treat Haitians, neighborhoods, civil society, or armed groups as monoliths. Attribute allegations and institutional assessments, protect survivor dignity, and distinguish Haitian ownership from endorsement of any particular political faction.',
        reviewCadenceDays: 30,
        reviewBy: '2026-09-08',
        coordinates: { latitude: 18.5944, longitude: -72.3074 },
        map: {
            mode: 'regional',
            locations: [
                { label: 'Port-au-Prince', latitude: 18.5944, longitude: -72.3074, role: 'National institutions and acute urban security pressures' },
                { label: 'Gonaïves / Artibonite', latitude: 19.45, longitude: -72.6833, role: 'Regional police capacity and civilian-protection pressures' },
                { label: 'Cap-Haïtien', latitude: 19.7594, longitude: -72.1982, role: 'Northern civic, economic, and institutional perspective' },
                { label: 'Santo Domingo', latitude: 18.4861, longitude: -69.9312, role: 'UNSOH back-office and cross-border support context' },
            ],
        },
        broadCategory: 'Geopolitics & Conflict',
        sources: [
            {
                title: '31st Anniversary of the PNH: Report on the General Operating Conditions of the Institution from June 2025 to June 2026',
                publisher: 'National Human Rights Defense Network (RNDDH)',
                publishedAt: '2026-06-12',
                url: 'https://web.rnddh.org/wp-content/uploads/2026/06/5-Rap-PNH-12Juin2026.ENG_.pdf',
                perspectiveType: 'local',
                perspective: 'Haitian civil-society monitoring of police working conditions, capacity, losses, and accountability needs',
                supports: [
                    'The report\'s methodology included 107 monitoring visits across 50 Haitian police posts.',
                    'It documents persistent personnel, equipment, infrastructure, logistics, and officer-safety constraints.',
                ],
            },
            {
                title: 'Noon briefing of 1 April 2026',
                publisher: 'Office of the UN Secretary-General',
                publishedAt: '2026-04-01',
                url: 'https://www.un.org/sg/en/content/highlight/2026-04-01.html',
                perspectiveType: 'institutional',
                perspective: 'United Nations account of UNSOH readiness and its support relationship with Haitian and international security institutions',
                supports: [
                    'UNSOH reported that it had met its timeline for logistical and operational support to the Gang Suppression Force.',
                    'The briefing identifies accommodation, medical, mobility, and back-office support functions rather than Haitian political outcomes.',
                ],
            },
            {
                title: 'World Report 2026: Haiti',
                publisher: 'Human Rights Watch',
                publishedAt: '2026-01-12',
                url: 'https://www.hrw.org/world-report/2026/country-chapters/haiti',
                perspectiveType: 'independent',
                perspective: 'Independent human-rights assessment of violence, security operations, displacement, accountability, and transitional governance',
                supports: [
                    'The chapter describes criminal-group abuses alongside alleged abuses and accountability gaps involving security and self-defense forces.',
                    'It documents the interaction between insecurity, displacement, public-service disruption, and the political transition.',
                ],
            },
        ],
        waypoints: [
            {
                nodeId: 'LatinAmerica',
                title: 'Begin With Haitian Institutional Capacity',
                perspectiveLabel: 'Haitian civil-society monitoring',
                perspectiveType: 'local',
                narration: 'RNDDH\'s field-based assessment finds that the Haitian National Police continues to operate with serious personnel, equipment, infrastructure, and safety constraints despite new training and international support.',
                focusQuestion: 'Which Haitian-defined capacity and accountability indicators should determine whether security assistance is working?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Define the Support Mission Narrowly',
                perspectiveLabel: 'UN operational mandate',
                perspectiveType: 'institutional',
                narration: 'The UN describes UNSOH as a logistical and operational support office; that claim should not be read as evidence that security, legitimacy, or civilian protection has already improved.',
                focusQuestion: 'How can international support be measured without confusing operational readiness with political success?',
            },
            {
                nodeId: 'Cartels',
                title: 'Center Civilian Protection and Accountability',
                perspectiveLabel: 'Independent human-rights review',
                perspectiveType: 'independent',
                narration: 'Human Rights Watch situates criminal-group violence within a broader pattern of displacement, disrupted services, security-operation harms, and weak accountability.',
                focusQuestion: 'What safeguards can reduce armed-group power without normalizing abuses by state or externally supported forces?',
            },
            {
                nodeId: 'LatinAmerica',
                title: 'Connect Security to Legitimate Governance',
                perspectiveLabel: 'Haitian ownership lens',
                perspectiveType: 'local',
                narration: 'The sources together show why security assistance must be evaluated against Haitian institutional capacity, public accountability, and an inclusive political process—not only deployments or equipment delivered.',
                focusQuestion: 'Who in Haiti defines legitimate progress, and how should excluded communities participate in that decision?',
            },
        ],
    },
    {
        id: 'amazon-indigenous-co-governance',
        title: 'Amazon: Indigenous Co-Governance After the Bogotá Declaration',
        subtitle: 'Turning regional recognition into durable authority, finance, and territorial protection',
        coverageRegion: 'Amazon Basin & South America',
        featured: true,
        regionTags: ['Amazon Basin', 'South America', 'Latin America'],
        issueDimensions: ['Indigenous governance', 'Forest protection', 'Climate finance', 'Regional cooperation'],
        actors: ['Amazon Indigenous peoples and organizations', 'COICA', 'Amazon Cooperation Treaty Organization', 'Amazonian national governments', 'Climate and conservation funders'],
        nexusNodeIds: ['LatinAmerica', 'UN_OPEC'],
        statusSummary: 'The eight Amazon Cooperation Treaty states adopted the Bogotá Declaration on 22 August 2025, calling for coordinated Amazon protection, social participation, and integration of scientific and traditional knowledge. One day earlier, COICA welcomed the consensus approval of the Amazonian Mechanism of Indigenous Peoples (MAPI), describing a co-presidency structure with governmental and Indigenous delegates. WRI Brasil argues that implementation also depends on finance reaching forest protection, restoration, Indigenous peoples, and local communities.',
        whyItMatters: 'The case moves beyond symbolic inclusion to ask whether Indigenous representatives receive continuing agenda-setting power, direct resources, and influence over decisions affecting territories and livelihoods.',
        updatedAt: '2025-08-22',
        confidence: 'high',
        uncertainty: 'MAPI procedures, national implementation, funding channels, and participation practices may evolve. Regional declarations and recommendations should not be described as automatically binding domestic law.',
        sensitivity: 'Indigenous peoples and organizations hold diverse positions and governance traditions. Avoid pan-Indigenous generalizations, obtain community-specific attribution, distinguish consultation from consent, and do not expose sensitive territorial information.',
        reviewCadenceDays: 90,
        reviewBy: '2026-11-07',
        coordinates: { latitude: -3.4653, longitude: -62.2159 },
        map: {
            mode: 'regional',
            locations: [
                { label: 'Leticia, Colombia', latitude: -4.215, longitude: -69.9406, role: 'Tri-border Amazon cooperation and Indigenous participation' },
                { label: 'Manaus, Brazil', latitude: -3.119, longitude: -60.0217, role: 'Urban, research, river, and forest-economy nexus' },
                { label: 'Puyo, Ecuador', latitude: -1.4924, longitude: -78.002, role: 'Amazon Indigenous organizational perspective' },
                { label: 'Iquitos, Peru', latitude: -3.7437, longitude: -73.2516, role: 'River-dependent communities and Peruvian Amazon governance' },
            ],
        },
        broadCategory: 'Environment & Energy',
        sources: [
            {
                title: 'COICA celebrates the approval of the Amazonian Mechanism of Indigenous Peoples (MAPI)',
                publisher: 'Coordinator of Indigenous Organizations of the Amazon River Basin (COICA)',
                publishedAt: '2025-08-21',
                url: 'https://coicamazonia.org/13933-2/',
                perspectiveType: 'local',
                perspective: 'Amazon-wide Indigenous organizational assessment of MAPI\'s design, legitimacy, and potential',
                supports: [
                    'COICA says MAPI was approved by consensus after 18 negotiating sessions.',
                    'COICA describes governmental and Indigenous co-presidency and a mandate to make recommendations on forests, territories, biodiversity, languages, and knowledge.',
                ],
            },
            {
                title: 'Bogotá Declaration: V Meeting of Presidents of the States Parties of the Amazon Cooperation Treaty',
                publisher: 'Amazon Cooperation Treaty Organization',
                publishedAt: '2025-08-22',
                url: 'https://otca.org/en/wp-content/uploads/2025/08/BOGOTA-DECLARATION_Presidential-Summit.pdf',
                perspectiveType: 'institutional',
                perspective: 'Joint intergovernmental commitments of the eight Amazon Cooperation Treaty states',
                supports: [
                    'The declaration calls for coordinated Amazon protection grounded in national sovereignty and regional cooperation.',
                    'It recognizes Indigenous and local knowledge, participation, territorial protection, climate action, biodiversity, and sustainable livelihoods.',
                ],
            },
            {
                title: 'Principais temas para acompanhar na COP30',
                publisher: 'WRI Brasil',
                publishedAt: null,
                sourceType: 'living-reference',
                reviewedAt: '2026-08-09',
                url: 'https://www.wribrasil.org.br/cop30/principais-temas',
                perspectiveType: 'independent',
                perspective: 'Independent policy analysis connecting nature protection, food systems, adaptation, finance, and Indigenous and local-community roles',
                supports: [
                    'The analysis argues that climate commitments require implementation through finance, adaptation, and national and subnational action.',
                    'It identifies Indigenous peoples and local communities as vital to forest protection and calls for stronger tenure and nature-finance support.',
                ],
            },
        ],
        waypoints: [
            {
                nodeId: 'LatinAmerica',
                title: 'Treat Participation as Governance',
                perspectiveLabel: 'COICA and Amazon Indigenous organizations',
                perspectiveType: 'local',
                narration: 'COICA presents MAPI as a permanent co-governance channel with paired governmental and Indigenous representation, while emphasizing that the mechanism must be strengthened in practice.',
                focusQuestion: 'What authority, selection rules, and accountability would make co-governance meaningful across distinct peoples and states?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Translate a Regional Declaration',
                perspectiveLabel: 'Amazon treaty institutions',
                perspectiveType: 'institutional',
                narration: 'The Bogotá Declaration joins forest, water, biodiversity, climate, social participation, and sustainable-development commitments within an intergovernmental framework that still relies on national implementation.',
                focusQuestion: 'Which commitments require common regional delivery, and which depend on enforceable domestic policy?',
            },
            {
                nodeId: 'LatinAmerica',
                title: 'Follow Authority and Finance',
                perspectiveLabel: 'Independent implementation analysis',
                perspectiveType: 'independent',
                narration: 'WRI Brasil\'s implementation lens highlights a practical test: whether finance and policy reach the communities protecting forests rather than stopping at high-level commitments.',
                focusQuestion: 'How should funding, tenure outcomes, and community control be tracked without imposing a single outside model?',
            },
            {
                nodeId: 'LatinAmerica',
                title: 'Protect Difference Within the Amazon',
                perspectiveLabel: 'Territorial and community diversity',
                perspectiveType: 'local',
                narration: 'A basin-wide mechanism can coordinate shared concerns, but it cannot substitute for the distinct rights, institutions, and consent processes of peoples in particular territories.',
                focusQuestion: 'How can regional coordination preserve community-specific authority and free, prior, and informed participation?',
            },
        ],
    },
    {
        id: 'rio-bravo-rio-grande-water-treaty',
        title: 'Rio Bravo / Rio Grande: Sharing Water Under Extreme Drought',
        subtitle: 'A binational treaty confronts hydrological scarcity and competing community needs',
        coverageRegion: 'United States–Mexico Borderlands',
        featured: true,
        regionTags: ['North America', 'Mexico', 'United States', 'Borderlands'],
        issueDimensions: ['Transboundary water', 'Climate adaptation', 'Agriculture', 'Urban growth'],
        actors: ['Mexican federal and state water authorities', 'United States federal and Texas water authorities', 'International Boundary and Water Commission', 'Farmers and irrigation districts', 'Border communities and cities'],
        nexusNodeIds: ['USA', 'LatinAmerica', 'UN_OPEC'],
        statusSummary: 'Mexico\'s National Water Commission said on 3 February 2026 that Mexico and the United States had agreed to a technical management plan under the 1944 Water Treaty amid extreme drought, with minimum deliveries conditioned on basin hydrology and Mexican human-consumption and agricultural needs. IBWC Minute 331 provides tools for earlier and more predictable deliveries, while Texas Tribune reporting shows how declining reliability affects farming, municipal growth, infrastructure, and the cost of alternative supplies in South Texas.',
        whyItMatters: 'The basin shows how a durable treaty must adapt to climate stress while balancing national obligations, human water needs, food production, ecosystems, and unequal local adjustment costs.',
        updatedAt: '2026-02-03',
        confidence: 'high',
        uncertainty: 'Reservoir levels, rainfall, allocations, deliveries, restrictions, and diplomatic understandings change quickly. Recheck IBWC/CILA hydrology and both governments\' statements before presenting current compliance.',
        sensitivity: 'Use both Rio Bravo and Rio Grande. Attribute treaty interpretations and avoid nationalist blame language; distinguish federal positions from those of states, tribes, irrigation districts, farmers, cities, and residents on both sides.',
        reviewCadenceDays: 30,
        reviewBy: '2026-09-08',
        coordinates: { latitude: 26.5, longitude: -99.1 },
        map: {
            mode: 'regional',
            locations: [
                { label: 'Ciudad Juárez / El Paso', latitude: 31.69, longitude: -106.42, role: 'Treaty administration and upper-border urban demand' },
                { label: 'Ojinaga / Presidio', latitude: 29.56, longitude: -104.41, role: 'Conchos–Rio Bravo inflow and rural border context' },
                { label: 'Falcón International Reservoir', latitude: 26.56, longitude: -99.16, role: 'Shared storage, allocation, and drought conditions' },
                { label: 'Matamoros / Brownsville', latitude: 25.9, longitude: -97.5, role: 'Lower-basin cities, agriculture, and delta ecosystems' },
            ],
        },
        broadCategory: 'Environment & Energy',
        sources: [
            {
                title: 'México y Estados Unidos acuerdan un plan técnico para la gestión del agua en la cuenca del Río Bravo conforme al Tratado de 1944',
                publisher: 'Comisión Nacional del Agua, Government of Mexico',
                publishedAt: '2026-02-03',
                url: 'https://www.gob.mx/conagua/prensa/mexico-y-estados-unidos-acuerdan-un-plan-tecnico-para-la-gestion-del-agua-en-la-cuenca-del-rio-bravo-conforme-al-tratado-de-1944-418614?idiom=es',
                perspectiveType: 'local',
                perspective: 'Mexican governmental account of drought constraints, sovereignty, treaty mechanisms, and domestic water priorities',
                supports: [
                    'Mexico describes a 2026 technical management plan agreed under the 1944 Water Treaty during extreme drought.',
                    'The statement conditions minimum deliveries on hydrology and emphasizes human consumption and agricultural production in Mexico.',
                ],
            },
            {
                title: 'IBWC Signs Minute 331 Focused on Improving Reliability, Predictability of Rio Grande Water Deliveries',
                publisher: 'International Boundary and Water Commission, United States and Mexico',
                publishedAt: '2024-11-09',
                url: 'https://www.ibwc.gov/wp-content/uploads/2024/11/IBWC-Signs-Minute-331-Focused-on-Improving-Reliability-Predictability-of-Rio-Grande-Water-Deliveries.pdf',
                perspectiveType: 'institutional',
                perspective: 'Binational treaty-body explanation of delivery flexibility, planning, conservation, and water-quality mechanisms',
                supports: [
                    'Minute 331 provides tools for earlier deliveries during a five-year treaty cycle, subject to agreed conditions.',
                    'It establishes work on conservation and environmental and water-quality issues while retaining treaty drought exceptions.',
                ],
            },
            {
                title: 'As the Rio Grande runs dry, South Texas leaders look to new water supplies to sustain growth',
                publisher: 'The Texas Tribune',
                publishedAt: '2025-05-15',
                url: 'https://www.texastribune.org/2025/05/15/texas-water-rio-grande-valley-drought/',
                perspectiveType: 'independent',
                perspective: 'Independent regional reporting on municipal, agricultural, infrastructure, affordability, and development tradeoffs',
                supports: [
                    'The reporting documents competition between agricultural and growing municipal demand in the Lower Rio Grande Valley.',
                    'It examines climate, infrastructure, groundwater treatment, reuse, and affordability as parts of the regional supply problem.',
                ],
            },
        ],
        waypoints: [
            {
                nodeId: 'LatinAmerica',
                title: 'Start With Mexico\'s Water Priorities',
                perspectiveLabel: 'Mexican basin-management position',
                perspectiveType: 'local',
                narration: 'Mexico\'s 2026 statement frames the plan around extreme drought, treaty cooperation, national sovereignty, and protection of human consumption and agricultural production.',
                focusQuestion: 'How should treaty delivery expectations adjust when the supplying basin also faces severe scarcity?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Use the Treaty\'s Adaptive Tools',
                perspectiveLabel: 'Binational treaty administration',
                perspectiveType: 'institutional',
                narration: 'Minute 331 is designed to improve timing and predictability through planning, flexibility, conservation work, and bilateral agreement—not to eliminate hydrological uncertainty.',
                focusQuestion: 'Which shared rules can create predictability without promising water that the basin does not contain?',
            },
            {
                nodeId: 'USA',
                title: 'See the Lower-Basin Tradeoffs',
                perspectiveLabel: 'Independent South Texas reporting',
                perspectiveType: 'independent',
                narration: 'Texas Tribune reporting connects river reliability to farms, cities, housing, infrastructure losses, alternative-water costs, and regional economic choices.',
                focusQuestion: 'Who pays when a region shifts from inexpensive river water to conservation, reuse, or treated groundwater?',
            },
            {
                nodeId: 'LatinAmerica',
                title: 'Manage One Basin, Not Two Narratives',
                perspectiveLabel: 'Cross-border community lens',
                perspectiveType: 'local',
                narration: 'The three readings show a shared hydrological system interpreted through different legal, national, agricultural, urban, and community priorities.',
                focusQuestion: 'What data and decision process would let communities on both sides evaluate scarcity and burden-sharing together?',
            },
        ],
    },
    {
        id: 'moldova-transnistria-energy-eu-accession',
        title: 'Moldova and Transnistria: Energy Resilience During EU Accession',
        subtitle: 'How an energy shock reshapes rights, leverage, and a contested political settlement',
        coverageRegion: 'Eastern Europe & Eurasia',
        featured: true,
        regionTags: ['Eastern Europe', 'Moldova', 'Transnistria'],
        issueDimensions: ['Energy security', 'EU accession', 'Human rights', 'Contested authority'],
        actors: ['Republic of Moldova authorities', 'Residents of the Transnistrian region', 'De facto Transnistrian authorities', 'European Union', 'Russia'],
        nexusNodeIds: ['Europe', 'Russia', 'UN_OPEC'],
        statusSummary: 'The Council of the EU reports that Moldova opened accession negotiations on the fundamentals cluster on 15 June 2026 and external-relations cluster 6 on 14 July 2026. Promo-LEX says the January 2025 loss of Russian gas supplies deepened energy, economic, and human-rights pressures in the Transnistrian region. ECFR independently analyzes the same shock as a source of political leverage affecting both the de facto region and Moldova\'s electricity system.',
        whyItMatters: 'Moldova links accession reform, energy diversification, Russian influence, the welfare and rights of people in a de facto separated region, and the unresolved question of reintegration.',
        updatedAt: '2026-07-14',
        confidence: 'high',
        uncertainty: 'Energy flows, tariffs, accession benchmarks, negotiations with the de facto authorities, and Russian policy can change quickly. Political-intent claims require clear attribution.',
        sensitivity: 'Use “Transnistrian region of the Republic of Moldova” for the internationally recognized legal context and “de facto Transnistrian authorities” for local control. Do not conflate residents with authorities or present any external actor\'s motive as established fact.',
        reviewCadenceDays: 45,
        reviewBy: '2026-09-23',
        coordinates: { latitude: 47.0105, longitude: 28.8638 },
        map: {
            mode: 'regional',
            locations: [
                { label: 'Chișinău', latitude: 47.0105, longitude: 28.8638, role: 'National accession, energy, and reintegration policy' },
                { label: 'Tiraspol', latitude: 46.8403, longitude: 29.6433, role: 'De facto administration and resident welfare' },
                { label: 'Cuciurgan power station', latitude: 46.635, longitude: 29.944, role: 'Electricity generation and cross-river dependency' },
                { label: 'Vulcănești', latitude: 45.684, longitude: 28.406, role: 'Romania interconnection and diversification corridor' },
            ],
        },
        broadCategory: 'Environment & Energy',
        sources: [
            {
                title: 'Human Rights in the Transnistrian Region of the Republic of Moldova: Retrospective of 2025',
                publisher: 'Promo-LEX Association',
                publishedAt: '2026-02-26',
                url: 'https://promolex.md/en/promo-lex-association-launches-the-report-human-rights-in-the-transnistrian-region-of-the-republic-of-moldova-retrospective-of-2025/',
                perspectiveType: 'local',
                perspective: 'Moldovan civil-society monitoring of resident welfare, rights, detention, education, and the local effects of the energy crisis',
                supports: [
                    'Promo-LEX reports that the January 2025 gas cutoff caused disconnections, job losses, and worsening living standards.',
                    'It documents alleged rights restrictions and recommends that human rights remain central in dialogue with Tiraspol.',
                ],
            },
            {
                title: 'Moldova',
                publisher: 'Council of the European Union',
                publishedAt: '2026-07-14',
                url: 'https://www.consilium.europa.eu/en/policies/moldova/',
                perspectiveType: 'institutional',
                perspective: 'Official EU record of Moldova\'s accession process, cooperation, security support, and negotiation milestones',
                supports: [
                    'The EU and Moldova opened negotiations on cluster 1 on 15 June 2026.',
                    'They opened cluster 6, covering external relations and foreign, security, and defense policy, on 14 July 2026.',
                ],
            },
            {
                title: 'Cold calculations: Why a freezing Transnistria helps Moscow',
                publisher: 'European Council on Foreign Relations',
                publishedAt: '2025-01-08',
                url: 'https://ecfr.eu/article/cold-calculations-why-a-freezing-transnistria-helps-moscow/',
                perspectiveType: 'independent',
                perspective: 'Independent policy analysis of energy interdependence, Russian leverage, EU options, and Moldovan political vulnerability',
                supports: [
                    'The analysis links the end of Russian gas transit to hardship in Transnistria and higher electricity costs in Moldova.',
                    'It presents possible Russian motives and EU response options as analysis rather than verified fact.',
                ],
            },
        ],
        waypoints: [
            {
                nodeId: 'Europe',
                title: 'Measure the Accession Track',
                perspectiveLabel: 'EU accession institutions',
                perspectiveType: 'institutional',
                narration: 'The EU records concrete 2026 milestones on the fundamentals and external-relations clusters, but opening negotiations is the start of benchmarked reform rather than a guarantee of membership.',
                focusQuestion: 'Which accession reforms can also strengthen energy resilience, democratic accountability, and public trust?',
            },
            {
                nodeId: 'Russia',
                title: 'Interrogate Energy Leverage',
                perspectiveLabel: 'Independent geopolitical analysis',
                perspectiveType: 'independent',
                narration: 'ECFR interprets the 2025 energy shock as a possible Russian pressure strategy; that motive remains an attributed analysis while the material energy disruption is documented separately.',
                focusQuestion: 'How can Moldova reduce external leverage without worsening conditions for residents across the Dniester?',
            },
            {
                nodeId: 'Europe',
                title: 'Center People in the De Facto Region',
                perspectiveLabel: 'Promo-LEX human-rights monitoring',
                perspectiveType: 'local',
                narration: 'Promo-LEX reports that the energy crisis magnified economic hardship and rights concerns for residents under de facto Transnistrian administration.',
                focusQuestion: 'How should assistance reach residents while avoiding reinforcement of coercive or unaccountable institutions?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Keep Settlement and Rights Connected',
                perspectiveLabel: 'Rules-based settlement lens',
                perspectiveType: 'institutional',
                narration: 'Energy stabilization, accession, and any settlement process have different timelines, but the sources show that each can affect rights, legitimacy, and bargaining power.',
                focusQuestion: 'What principles should govern reintegration dialogue when immediate welfare and long-term political status are intertwined?',
            },
        ],
    },
    {
        id: 'high-seas-bbnj-implementation',
        title: 'High Seas: Implementing the BBNJ Agreement',
        subtitle: 'From treaty entry into force to inclusive institutions, finance, and ocean protection',
        coverageRegion: 'Global Oceans',
        featured: true,
        regionTags: ['Global', 'High Seas', 'Pacific Islands', 'Global South'],
        issueDimensions: ['Ocean governance', 'Biodiversity', 'Benefit sharing', 'Capacity building'],
        actors: ['BBNJ Agreement parties', 'Pacific small island developing states', 'Indigenous peoples and local communities', 'Ocean science networks', 'Existing maritime and sectoral bodies'],
        nexusNodeIds: ['UN_OPEC', 'AsiaPacific', 'Africa'],
        statusSummary: 'The UN records that the BBNJ Agreement entered into force on 17 January 2026. IISD\'s independent summary of the third Preparatory Commission reports agreement on several institutional and financial preparations but unresolved provisions for COP1. Pacific small island developing states proposed stronger participation by Indigenous peoples and local communities, including an advisory mechanism, expert rosters, and opportunities to present concerns before recommendations are finalized.',
        whyItMatters: 'The treaty\'s effect will depend on who participates, how benefits and capacity are shared, how institutions coordinate, and whether parties turn global rules into legitimate conservation decisions.',
        updatedAt: '2026-04-06',
        confidence: 'high',
        uncertainty: 'COP1 decisions, participation rules, subsidiary-body design, finance, the secretariat seat, and future area-based measures remain subject to negotiation. Entry into force did not itself create a particular marine protected area.',
        sensitivity: 'The agreement binds its parties and concerns areas beyond national jurisdiction; do not imply universal participation or automatic precedence over other competent bodies. Treat Indigenous peoples, local communities, coastal states, and small island states as distinct constituencies.',
        reviewCadenceDays: 90,
        reviewBy: '2026-11-07',
        map: {
            mode: 'global',
            locations: [
                { label: 'United Nations Headquarters, New York', latitude: 40.7505, longitude: -73.9934, role: 'Preparatory Commission and COP institutional process' },
                { label: 'Koror, Palau', latitude: 7.3419, longitude: 134.4793, role: 'Pacific small-island-state governance perspective' },
                { label: 'Suva, Fiji', latitude: -18.1248, longitude: 178.4501, role: 'Pacific regional capacity and community-participation perspective' },
                { label: 'Cape Town, South Africa', latitude: -33.9249, longitude: 18.4241, role: 'African coastal science, capacity, and implementation perspective' },
            ],
        },
        broadCategory: 'Environment & Energy',
        sources: [
            {
                title: 'Proposals by the Pacific Small Island Developing States',
                publisher: 'Pacific Small Island Developing States',
                publishedAt: '2026-03-25',
                url: 'https://www.un.org/bbnjagreement/sites/default/files/2026-03/PSIDS_SubBodiesCorr_25March.pdf',
                perspectiveType: 'local',
                perspective: 'Pacific small-island-state proposals for Indigenous, local-community, and traditional-knowledge participation in BBNJ institutions',
                supports: [
                    'The proposal seeks an advisory mechanism and expert participation relating to Indigenous peoples, local communities, and traditional knowledge.',
                    'It calls for affected communities to have an adequate opportunity to present concerns and alternatives before recommendations are finalized.',
                ],
            },
            {
                title: 'BBNJ Agreement',
                publisher: 'United Nations, Division for Ocean Affairs and the Law of the Sea',
                publishedAt: null,
                sourceType: 'living-reference',
                reviewedAt: '2026-08-09',
                milestoneDate: '2026-01-17',
                milestoneLabel: 'Agreement entered into force',
                url: 'https://www.un.org/bbnjagreement/en',
                perspectiveType: 'institutional',
                perspective: 'Official treaty portal and institutional record for adoption, parties, entry into force, and implementation preparations',
                supports: [
                    'The BBNJ Agreement was adopted on 19 June 2023.',
                    'It entered into force on 17 January 2026 after the required treaty threshold and waiting period.',
                ],
            },
            {
                title: 'Summary of the Third Session of the Preparatory Commission for the Entry into Force of the BBNJ Agreement',
                publisher: 'Earth Negotiations Bulletin, International Institute for Sustainable Development',
                publishedAt: '2026-04-06',
                url: 'https://enb.iisd.org/sites/default/files/2026-04/enb25262e.pdf',
                perspectiveType: 'independent',
                perspective: 'Independent negotiation reporting on areas of agreement, unresolved provisions, participation, finance, and the path to COP1',
                supports: [
                    'PrepCom III agreed on several operational preparations while forwarding unresolved institutional and financial provisions to COP1.',
                    'The report distinguishes treaty entry into force from the later decisions needed for implementation.',
                ],
            },
        ],
        waypoints: [
            {
                nodeId: 'UN_OPEC',
                title: 'Separate Entry Into Force From Delivery',
                perspectiveLabel: 'Official treaty process',
                perspectiveType: 'institutional',
                narration: 'The agreement entered into force in January 2026, but its institutions, funding, procedures, and conservation decisions still require implementation by parties.',
                focusQuestion: 'Which early institutional decisions will most influence whether the treaty produces credible outcomes?',
            },
            {
                nodeId: 'AsiaPacific',
                title: 'Design Participation Into the System',
                perspectiveLabel: 'Pacific small-island-state proposal',
                perspectiveType: 'local',
                narration: 'PSIDS proposals seek structured roles for Indigenous peoples, local communities, and traditional knowledge rather than participation limited to observation.',
                focusQuestion: 'How should expertise, representation, consent, and accountability operate when decisions affect communities with deep ocean relationships?',
            },
            {
                nodeId: 'Africa',
                title: 'Make Capacity and Benefits Operational',
                perspectiveLabel: 'Developing coastal-state implementation lens',
                perspectiveType: 'local',
                narration: 'The agreement\'s legitimacy depends partly on whether states and communities with fewer scientific and financial resources can participate in research, governance, and benefit sharing.',
                focusQuestion: 'What funding and technology-transfer indicators would demonstrate more equal implementation capacity?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Track the Unresolved Rules',
                perspectiveLabel: 'Independent negotiation record',
                perspectiveType: 'independent',
                narration: 'IISD reports both negotiated progress and bracketed provisions that COP1 must resolve, preventing a premature claim that the governance architecture is complete.',
                focusQuestion: 'Where could procedural disagreement most directly delay conservation, finance, or accountable decision-making?',
            },
        ],
    },
    {
        id: 'who-pathogen-access-benefit-sharing',
        title: 'Global Health: Pathogen Access and Benefit Sharing',
        subtitle: 'Can faster scientific sharing be matched by fair access to vaccines, diagnostics, and therapeutics?',
        coverageRegion: 'Global',
        featured: true,
        regionTags: ['Global', 'Africa', 'Global South', 'Geneva'],
        issueDimensions: ['Global health governance', 'Pathogen access', 'Benefit sharing', 'Regional manufacturing'],
        actors: ['WHO member states', 'African Group of negotiators', 'Public-health laboratories', 'Vaccine, diagnostics, and therapeutics developers', 'Patients and health systems'],
        nexusNodeIds: ['UN_OPEC', 'BiotechHub', 'Africa'],
        statusSummary: 'WHO reported on 20 July 2026 that member states had advanced but not completed negotiations on the Pathogen Access and Benefit Sharing annex to the WHO Pandemic Agreement; the eighth negotiating meeting is scheduled for 14–18 September 2026. The African Group says its common position is intended to protect continental interests and avoid a repeat of COVID-era inequities. A peer-reviewed BMJ analysis identifies equity, technology transfer, regional manufacturing, financing, national implementation, and accountability as continuing tests.',
        whyItMatters: 'PABS sits at the core of a global bargain: rapid and safe sharing for research and response in exchange for fair, timely access to the health products and other benefits that sharing makes possible.',
        updatedAt: '2026-07-20',
        confidence: 'high',
        uncertainty: 'The annex text, contractual terms, laboratory-network design, definitions of benefits, and adoption timetable remain under negotiation. Positions may change at the September session or a later World Health Assembly.',
        sensitivity: 'Keep coverage at the governance level: do not include operational details that could facilitate pathogen acquisition, modification, or misuse. Attribute negotiating positions, distinguish equity concerns from scientific claims, and avoid treating countries, researchers, manufacturers, or regions as monoliths.',
        reviewCadenceDays: 30,
        reviewBy: '2026-09-08',
        map: {
            mode: 'global',
            locations: [
                { label: 'WHO, Geneva', latitude: 46.232, longitude: 6.134, role: 'Member-state negotiations and institutional coordination' },
                { label: 'Africa CDC, Addis Ababa', latitude: 9.019, longitude: 38.752, role: 'Continental public-health coordination and negotiating perspective' },
                { label: 'Cape Town, South Africa', latitude: -33.9249, longitude: 18.4241, role: 'Health-equity advocacy and regional manufacturing perspective' },
                { label: 'Jakarta, Indonesia', latitude: -6.2088, longitude: 106.8456, role: 'Global South pathogen-sovereignty and benefit-sharing perspective' },
            ],
        },
        broadCategory: 'Health & Society',
        sources: [
            {
                title: 'African Group high level preparations ahead of the resumed 6th session on the PABS System',
                publisher: 'African Union',
                publishedAt: '2026-04-28',
                url: 'https://au.int/sites/default/files/pressreleases/46323-pr-Press_release_Ambassadors_workshop_23_April_2026_E_FINAL.pdf',
                perspectiveType: 'local',
                perspective: 'African Group account of continental coordination, negotiating priorities, and equity concerns',
                supports: [
                    'The African Group organized a common negotiating position ahead of resumed PABS talks.',
                    'Its stated objective is to safeguard African interests and prevent a repeat of inequities experienced during COVID-19.',
                ],
            },
            {
                title: 'WHO Member States continue negotiations on the Pathogen Access and Benefit Sharing Annex',
                publisher: 'World Health Organization',
                publishedAt: '2026-07-20',
                url: 'https://www.who.int/news/item/20-07-2026-who-member-states-continue-negotiations-on-the-pathogen-access-and-benefit-sharing-annex',
                perspectiveType: 'institutional',
                perspective: 'Official account of negotiation status, unresolved design questions, and the next scheduled meeting',
                supports: [
                    'Member states advanced but did not finalize the PABS annex during the July 2026 meeting.',
                    'Negotiations covered contractual arrangements, laboratory networks, shared materials and information, and definitions of benefits; the next meeting is scheduled for September 2026.',
                ],
            },
            {
                title: 'WHO Pandemic Agreement is only the beginning: strengthening implementation to protect global health',
                publisher: 'The BMJ',
                publishedAt: '2026-02-17',
                url: 'https://www.bmj.com/content/392/bmj-2025-086069',
                perspectiveType: 'independent',
                perspective: 'Peer-reviewed analysis of equity, intellectual property, technology transfer, regional manufacturing, financing, and accountability',
                supports: [
                    'The authors identify unresolved PABS equity and trust concerns as a barrier to implementation.',
                    'They argue for regional manufacturing, stronger Global South participation, national investment, monitoring, and accountability.',
                ],
            },
        ],
        waypoints: [
            {
                nodeId: 'UN_OPEC',
                title: 'Define the Global Bargain',
                perspectiveLabel: 'WHO member-state process',
                perspectiveType: 'institutional',
                narration: 'WHO describes PABS as a reciprocal framework for rapid, safe sharing and fair access to resulting vaccines, diagnostics, therapeutics, and other agreed benefits; key terms remain unsettled.',
                focusQuestion: 'Which obligations must be predictable in advance for both rapid sharing and equitable response?',
            },
            {
                nodeId: 'Africa',
                title: 'Treat Equity as System Design',
                perspectiveLabel: 'African Group negotiating perspective',
                perspectiveType: 'local',
                narration: 'The African Group frames PABS around bargaining power, access, and preventing a repetition of pandemic-era inequity—not as a secondary distribution issue after research is complete.',
                focusQuestion: 'How should benefits be allocated so that countries providing materials and information can trust the system during an emergency?',
            },
            {
                nodeId: 'BiotechHub',
                title: 'Connect Research Incentives and Access',
                perspectiveLabel: 'Independent political-economy analysis',
                perspectiveType: 'independent',
                narration: 'The BMJ analysis places manufacturer incentives, public investment, intellectual property, technology transfer, and regional production within the same implementation problem.',
                focusQuestion: 'Which combination of contracts, financing, licensing, and manufacturing commitments can sustain innovation and timely access?',
            },
            {
                nodeId: 'UN_OPEC',
                title: 'Build Verifiable Accountability',
                perspectiveLabel: 'Independent implementation lens',
                perspectiveType: 'independent',
                narration: 'Adoption alone cannot establish trust; the BMJ authors argue that national implementation, financing, monitoring, and independent review will determine whether commitments change outcomes.',
                focusQuestion: 'What should governments, WHO, laboratories, and participating manufacturers report so performance can be evaluated without exposing sensitive information?',
            },
        ],
    },
];
